In [23]:
import pandas as pd
import numpy as np
import pickle

with open("HPcharacters.pickle", "rb") as file:
    HPdata = pickle.load(file)

df = pd.DataFrame(HPdata)
df

,id,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,wand,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image
0,9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8,Harry Potter,"[The Boy Who Lived, The Chosen One]",human,male,Gryffindor,31-07-1980,1980.0,True,half-blood,green,black,"{'wood': 'holly', 'core': 'phoenix feather', '...",stag,True,False,Daniel Radcliffe,[],True,https://ik.imagekit.io/hpapi/harry.jpg
1,4c7e6819-a91a-45b2-a454-f931e4a7cce3,Hermione Granger,[],human,female,Gryffindor,19-09-1979,1979.0,True,muggleborn,brown,brown,"{'wood': 'vine', 'core': 'dragon heartstring',...",otter,True,False,Emma Watson,[],True,https://ik.imagekit.io/hpapi/hermione.jpeg
2,c3b1f9a5-b87b-48bf-b00d-95b093ea6390,Ron Weasley,[Dragomir Despard],human,male,Gryffindor,01-03-1980,1980.0,True,pure-blood,blue,red,"{'wood': 'willow', 'core': 'unicorn tail-hair'...",Jack Russell terrier,True,False,Rupert Grint,[],True,https://ik.imagekit.io/hpapi/ron.jpg
3,af95bd8a-dfae-45bb-bc69-533860d34129,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980.0,True,pure-blood,grey,blonde,"{'wood': 'hawthorn', 'core': 'unicorn tail-hai...",,True,False,Tom Felton,[],True,https://ik.imagekit.io/hpapi/draco.jpg
4,ca3827f0-375a-4891-aaa5-f5e8a5bad225,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925.0,True,half-blood,,black,"{'wood': 'fir', 'core': 'dragon heartstring', ...",tabby cat,False,True,Dame Maggie Smith,[],True,https://ik.imagekit.io/hpapi/mcgonagall.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,dcdc063e-cf3e-48fc-b777-65922e899b38,Albus Severus Potter,[Al],human,male,Slytherin,None,NaN,True,half-blood,green,black,"{'wood': '', 'core': '', 'length': None}",,True,False,Arthur Bowen,[],True,
398,e4653b01-76a5-4769-a6a2-1f2efaf89cbb,Rose Weasley,[],human,female,Gryffindor,None,NaN,True,half-blood,,red,"{'wood': '', 'core': '', 'length': None}",,True,False,Helena Barlow,[],True,
399,2b203c7e-7b3d-4f27-8b3c-11473904da73,Hugo Weasley,[],human,male,,None,NaN,True,half-blood,,brown,"{'wood': '', 'core': '', 'length': None}",,True,False,Ryan Turner,[],True,
400,7f2f6207-8998-4f98-92c2-8d02898a82eb,Scorpius Malfoy,[Scorpius Hyperion Malfoy],human,male,Slytherin,None,NaN,True,pure-blood,grey,blond,"{'wood': '', 'core': '', 'length': None}",,True,False,Bertie Gilbert,[],True,
401,57fe29d4-312a-4711-bd9a-c320253d9176,Victoire Weasley,[],human,female,,None,NaN,True,,,blonde,"{'wood': '', 'core': '', 'length': None}",,True,False,,[],True,

In [25]:
df =df.drop(columns=["id", "alternate_names", "gender", "wand", "actor", "alternate_actors", "image"])
df

,name,species,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,patronus,hogwartsStudent,hogwartsStaff,alive
0,Harry Potter,human,Gryffindor,31-07-1980,1980.0,True,half-blood,green,black,stag,True,False,True
1,Hermione Granger,human,Gryffindor,19-09-1979,1979.0,True,muggleborn,brown,brown,otter,True,False,True
2,Ron Weasley,human,Gryffindor,01-03-1980,1980.0,True,pure-blood,blue,red,Jack Russell terrier,True,False,True
3,Draco Malfoy,human,Slytherin,05-06-1980,1980.0,True,pure-blood,grey,blonde,,True,False,True
4,Minerva McGonagall,human,Gryffindor,04-10-1925,1925.0,True,half-blood,,black,tabby cat,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,Albus Severus Potter,human,Slytherin,None,NaN,True,half-blood,green,black,,True,False,True
398,Rose Weasley,human,Gryffindor,None,NaN,True,half-blood,,red,,True,False,True
399,Hugo Weasley,human,,None,NaN,True,half-blood,,brown,,True,False,True
400,Scorpius Malfoy,human,Slytherin,None,NaN,True,pure-blood,grey,blond,,True,False,True
401,Victoire Weasley,human,,None,NaN,True,,,blonde,,True,False,True

# Introduksjon til *pan*el *da*ta: Pandas

Nyttig ressurs: [https://pandas.pydata.org/docs/user_guide/](https://pandas.pydata.org/docs/user_guide/)

* Pandas er et bibliotek for python for å manipulere og analysere data
* Vi bruker pandas til å laste inn eller lage datasett
    - Rydde opp i data
    - Få det over på annet format
    - Gjøre statistikk
    - Plotte data

* Vi importerer pandas med som regel med `import pandas as pd`
* Pandas er bygd på numpy, så man trenger ofte også å bruke numpy

In [33]:
#EKSEMPEL

import pandas as pd
import numpy as np
import pickle

with open("HPcharacters.pickle", "rb") as file:
    HPdata = pickle.load(file)

df = pd.DataFrame(HPdata)
df

,id,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,wand,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image
0,9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8,Harry Potter,"[The Boy Who Lived, The Chosen One]",human,male,Gryffindor,31-07-1980,1980.0,True,half-blood,green,black,"{'wood': 'holly', 'core': 'phoenix feather', '...",stag,True,False,Daniel Radcliffe,[],True,https://ik.imagekit.io/hpapi/harry.jpg
1,4c7e6819-a91a-45b2-a454-f931e4a7cce3,Hermione Granger,[],human,female,Gryffindor,19-09-1979,1979.0,True,muggleborn,brown,brown,"{'wood': 'vine', 'core': 'dragon heartstring',...",otter,True,False,Emma Watson,[],True,https://ik.imagekit.io/hpapi/hermione.jpeg
2,c3b1f9a5-b87b-48bf-b00d-95b093ea6390,Ron Weasley,[Dragomir Despard],human,male,Gryffindor,01-03-1980,1980.0,True,pure-blood,blue,red,"{'wood': 'willow', 'core': 'unicorn tail-hair'...",Jack Russell terrier,True,False,Rupert Grint,[],True,https://ik.imagekit.io/hpapi/ron.jpg
3,af95bd8a-dfae-45bb-bc69-533860d34129,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980.0,True,pure-blood,grey,blonde,"{'wood': 'hawthorn', 'core': 'unicorn tail-hai...",,True,False,Tom Felton,[],True,https://ik.imagekit.io/hpapi/draco.jpg
4,ca3827f0-375a-4891-aaa5-f5e8a5bad225,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925.0,True,half-blood,,black,"{'wood': 'fir', 'core': 'dragon heartstring', ...",tabby cat,False,True,Dame Maggie Smith,[],True,https://ik.imagekit.io/hpapi/mcgonagall.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,dcdc063e-cf3e-48fc-b777-65922e899b38,Albus Severus Potter,[Al],human,male,Slytherin,None,NaN,True,half-blood,green,black,"{'wood': '', 'core': '', 'length': None}",,True,False,Arthur Bowen,[],True,
398,e4653b01-76a5-4769-a6a2-1f2efaf89cbb,Rose Weasley,[],human,female,Gryffindor,None,NaN,True,half-blood,,red,"{'wood': '', 'core': '', 'length': None}",,True,False,Helena Barlow,[],True,
399,2b203c7e-7b3d-4f27-8b3c-11473904da73,Hugo Weasley,[],human,male,,None,NaN,True,half-blood,,brown,"{'wood': '', 'core': '', 'length': None}",,True,False,Ryan Turner,[],True,
400,7f2f6207-8998-4f98-92c2-8d02898a82eb,Scorpius Malfoy,[Scorpius Hyperion Malfoy],human,male,Slytherin,None,NaN,True,pure-blood,grey,blond,"{'wood': '', 'core': '', 'length': None}",,True,False,Bertie Gilbert,[],True,
401,57fe29d4-312a-4711-bd9a-c320253d9176,Victoire Weasley,[],human,female,,None,NaN,True,,,blonde,"{'wood': '', 'core': '', 'length': None}",,True,False,,[],True,

In [30]:
sdata = {"frukt": ["epler", "pærer", "moreller", "rips"], "produksjon": [12,23,1,9], "subsidiert": [True, False, True, False], "pris": [10, 25, 40, 5]}
df_bilde = pd.DataFrame(sdata)
df_bilde

      frukt  produksjon  subsidiert  pris
0     epler          12        True    10
1     pærer          23       False    25
2  moreller           1        True    40
3      rips           9       False     5

In [31]:
sdata2 = { "produksjon": [12,23,1,9], "subsidiert": [True, False, True, False], "pris": [10, 25, 40, 5]}
df_bilde2 = pd.DataFrame(sdata2, index = ["epler", "pærer", "moreller", "rips"])
df_bilde2

          produksjon  subsidiert  pris
epler             12        True    10
pærer             23       False    25
moreller           1        True    40
rips               9       False     5

* Pandas er bygd opp av objekter kalt *DataFrames* og *Series*
* Vi jobber for det meste med DataFrames
* DataFrames likner litt på hvordan man strukturerer data i feks excel
* De består av rader, og kolonner kalt *Series*
<img src="img/dfnavn1.jpg" width="550">

* Hvert rad har en index
* Ut av boksen har radene indeks med heltall 0,1,2,3...
* Man kan også ha navn på radene (indeks er liste med strenger) slik som kolonnenavnene
![dataframe_indeksnavn](img/dfnavn2.png)

## Pandas Series
* Pandas series er som kolonnene i en tabell
* Dataserier har en *index*, et *navn* og *data* av en eller annen datatype (`dtype`)
* Vi lager serier med `pd.Series( ... )`

In [42]:
dataserie = pd.Series([1,2,3,4,5])
dataserie_2 = pd.Series(["Bil", "Båt", "Sykkel", "Tog", "Fly"])
dataserie

0    1
1    2
2    3
3    4
4    5
dtype: int64

* Her mangler vi navn på serien

* Vi kan navngi serien ved å gi *keyword* argumentet "name"
* `pd.Series(data, name="Navnet")`

In [46]:
dataserie = pd.Series([1,2,3,4,5], name="Heltall")
dataserie

0    1
1    2
2    3
3    4
4    5
Name: Heltall, dtype: int64

* Vi kan gi en annen indeks med *keyword* argumentet "index"
* `pd.Series(data, name="Navnet", index = [ .... ])`

In [45]:
dataserie = pd.Series([1,2,3,4,5], name="Heltall", index=["en", "to", "tre", "fire", "fem"])
dataserie

en      1
to      2
tre     3
fire    4
fem     5
Name: Heltall, dtype: int64

* Tidligere eksempel gir lister til `pd.Series()`
* Det kan være lurt å lage variabler med listene som skal bruke
* Når det passer seg bør listene være numpy *arrays*

In [66]:
data = np.array([1,2,3,4,5], dtype="int64")
navn = "heltall"
indeks = np.array(["en", "to", "tre", "fire", "fem"])
dataserie = pd.Series(data, name=navn, index=indeks)
#data[2] = 55
dataserie

en      1
to      2
tre     3
fire    4
fem     5
Name: heltall, dtype: int64

* Merk at dersom vi forandrer datavariabelen, forandres også pandas serien
* Dersom dette ikke er ønskelig kan vi bruke `copy=True` når vi lager serien

In [67]:
dataserie = pd.Series(data, name=navn, index=indeks, copy=True)
print(dataserie)
data[2]=66
dataserie

en      1
to      2
tre     3
fire    4
fem     5
Name: heltall, dtype: int64

en      1
to      2
tre     3
fire    4
fem     5
Name: heltall, dtype: int64

### Oppgave 1:

* Lag dataserien under i pandas:
![oppg1](img/series_oppg1.png)

In [70]:
data = np.array([187,177,195,159], dtype="float64")
indeks = ["Per", "Pål", "Espen", "Askeladd"]
navn = "EventyrfigurHøyde"
dataserie = pd.Series(data, name=navn, index=indeks, copy=True)
dataserie

Per         187.0
Pål         177.0
Espen       195.0
Askeladd    159.0
Name: EventyrfigurHøyde, dtype: float64

* Vi kan lage serier også med dictionaries `{indeks0: data0, indeks1: data1}`
* Da blir indeksen satt til nøklene i dictionary'en

In [75]:
transport_data = {"land": "bil", "sjø": "båt", "luft": "fly"}
serie = pd.Series(transport_data, name="transportmetoder")
serie

land    bil
sjø     båt
luft    fly
Name: transportmetoder, dtype: object

### Oppgave 2:

* Lag samme dataserie som tidligere i pandas
* Denne gangen bruk en dictionary til å sette data/indeks
![oppg1](img/series_oppg1.png)

In [80]:
data =  {"Per": 187, "Pål": 177, "Espen": 195, "Askeladd": 159}
navn = "EventyrfigurHøyde"
dataserie = pd.Series(data, name=navn, dtype="float64")
dataserie

Per         187.0
Pål         177.0
Espen         NaN
Askeladd    159.0
Name: EventyrfigurHøyde, dtype: float64

* Dersom vi mangler noe data for en indeks bruker vi `np.NaN`som data

In [29]:
data =  {"Per": 187, "Pål": 177, "Espen": np.NaN, "England": 159}
navn = "EventyrfigurHøyde"
dataserie = pd.Series(data, name=navn, dtype="float64")
dataserie

Per        187.0
Pål        177.0
Espen        NaN
England    159.0
Name: EventyrfigurHøyde, dtype: float64

## Pandas DataFrame

* Vi er som regel interessert i å jobbe med DataFrames, en samling av serier
* Vi lager de med `pd.DataFrames(data, index=None, columns=None, dtype=None, copy=None)`
* Vi har de samme feltene som serier, men dataen er nå *todimensjonal*

* `data` variabelen vi fyller dataframen vår med kan ha flere former:
 - 2d-array
 - dictionary -> `{col0: [data0], col1: [data1], ...}`
 - pandas Series

In [3]:
import pandas as pd
import numpy as np
data1 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(data1)
df1 = pd.DataFrame(data1, columns=["høyde", "vekt", "omkrets"], index=range(2,5))
df1

[[1 2 3]
 [4 5 6]
 [7 8 9]]

   høyde  vekt  omkrets
2      1     2        3
3      4     5        6
4      7     8        9

In [28]:
data2 = {"BNP": [1,2,3,4], "levealder": [88,88,99,102], 
         "styresett": ["demokrati", "diktatur", "demokrati", "monarki"]}
df2 = pd.DataFrame(data2, index=["Norge", "Uganda", "Sverige", "England"])
df2

         BNP  levealder  styresett
Norge      1         88  demokrati
Uganda     2         88   diktatur
Sverige    3         99  demokrati
England    4        102    monarki

In [24]:
indeks = ["BNP", "levealder", "styresett"]
serie1 = pd.Series([1,88,"demokrati"], name="Norge", index =indeks )
serie2 = pd.Series([2,88,"diktatur"], name="UGanda", index=indeks)
df3 = pd.DataFrame([serie1, serie2])
df3

        BNP  levealder  styresett
Norge     1         88  demokrati
UGanda    2         88   diktatur

### Oppgave 3:


Under har vi et lite pandas dataframe.
![oppg1](img/dataframe_oppg3.png)

Prøv å lage tabellen ved å bruke metodene over

In [45]:
testdat = {"Arbeidsledighet": ["2.0%","2.3%","2.6%","3.1%"],
           "Konkurser": [100,120,250,180],
           "BNP": [2e6,3e6,1.8e6,1.5e6]
          }
testdf = pd.DataFrame(testdat, index=range(2010,2014))
testdf

     Arbeidsledighet  Konkurser        BNP
2010            2.0%        100  2000000.0
2011            2.3%        120  3000000.0
2012            2.6%        250  1800000.0
2013            3.1%        180  1500000.0

## Slå opp i Frame/Series

### Series
* Vi kan slå opp verdi nr. $i$ med serie[$i$]
* Eller vi kan bruke indeks: serie["indeks"]

### Dataframes
* Vi får tak i kolonne med `df["kolonnenavn"]`
* Vi får tak i rad med df.loc["rad_indeks"]
* Vi kan få tak i rad med df.iloc[i] hvor i er mellom 0 og antall rader i tabellen
* Vi får tak i et datapunkt med df.loc["rad", "kolonne"]

In [22]:
print(f"Levealder i {serie1.name} er {serie1['levealder']}")
print(f"Levealder i {serie2.name} er {serie2[1]}")

Levealder i Norge er 88
Levealder i UGanda er 88

In [42]:
#kolonne BNP:
print("Kolonne 'BNP':\n", df2['BNP'])

#Rad med indeks
print("\nRad 'Sverige':\n", df2.loc['Sverige'])

#Rad med radnummer
print("\nRad nr. 3:\n", df2.iloc[2])

#Levalder i England:
print("\nLevealder i England er:", df2.loc["England", "levealder"])
df2

Kolonne 'BNP':
 Norge      1
Uganda     2
Sverige    3
England    4
Name: BNP, dtype: int64

Rad 'Sverige':
 BNP                  3
levealder           99
styresett    demokrati
Name: Sverige, dtype: object

Rad nr. 3:
 BNP                  3
levealder           99
styresett    demokrati
Name: Sverige, dtype: object

Levealder i England er: 102

         BNP  levealder  styresett
Norge      1         88  demokrati
Uganda     2         88   diktatur
Sverige    3         99  demokrati
England    4        102    monarki

### Oppg 4

Se at du kan slå opp fra oppgave 3 og hente ut en gitt kolonne, rad eller datapunkt

## Manipulere Frame/Series

Vi vil kanskje kunne trenge å:
* Forandre indeks, navn på serie, eller navn på kolonner
* Legge til rad, eller kolonne til dataframe
* Bytte om på rad/kolonne
* Fjerne rad eller kolonne

In [46]:
data_land = ["England", "Norge", "Sverige"]
land = pd.Series(data_land)

#Forandre/hente navn på serie med min_serie.name
land.name = "land"

indeks = ["GB", "NO", "SE"]

#Hent eller sett en series index med min_sere.index
land.index= indeks
land["NO"] = "Danmark"

#land.index[1] = "DK" Vi må skifte hele indeksen
indeks = ["GB", "DK", "SE"]
land.index = indeks

#Vi legger til nye element på samme måte som i dictionaries
land["NOO"]= "Norge" # Legg til nytt element.

land = land.rename({"NOO": "NU"}) #Skift navn 
#Merk at .rename() ikke skifter navnet, men returnerer en ny Serie med skiftet
land.rename({"NU": "NO"}, inplace=True) #inplace=True gjør "fikser" på dette
land

GB    England
DK    Danmark
SE    Sverige
NO      Norge
Name: land, dtype: object

In [80]:
data_innbyggere = [56, 6, 10]
land_innbyggere = pd.Series(data_innbyggere, name="innbyggere", index=indeks)

df_land = pd.DataFrame([land, land_innbyggere])
df_land = df_land.T # Bytter om på kolonner/rader (Transponerer)
df_land = df_land.rename(columns=({'land': 'navn'})) #Nytt navn til kolonne
df_land.loc['DK', 'navn'] = "Island" #Skifter landenavn til island
df_land.loc['DK', 'innbyggere'] = 0.4 #antall innbyggere til 0.4
df_land.rename(index={'DK': 'IS'}, inplace=True) #Nytt navn på indeks "DK"
df_land.loc["NO", "innbyggere"] = 5 # Oppdaterer data

df_land.loc["DK"] = ["Danmark", 6] #Legg til ny rad
df_land.loc["DE"] = {"navn": "Tyskland"} #Legg til rad med manglende data
df_land.loc["DE", "innbyggere"] = 80 #Oppdater data
df_land

        navn innbyggere
GB   England       56.0
IS    Island        0.4
SE   Sverige       10.0
NO     Norge          5
DK   Danmark          6
DE  Tyskland         80

### Oppg 5:
Ta utgangpunkt i tabellen over for å lage tabellen under
![oppg5](img/df_oppg5v2.png)

les [her](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html) for å finne ut hvordan du legger til en kolonne med `insert`

In [81]:
df_land.rename(columns=({"innbyggere": "populasjonsstørrelse"}), inplace=True)
df_land.drop(index=['NO'], inplace=True)
df_land.insert(2,"arbeidsledighet", ["1.0%","4.9%","3.2%","1.6%","12.5%" ])
df_land.loc["DE", "populasjonsstørrelse"]  = 83
df_land.loc["US"] = ["USA", 300, "50%"]
df_land

        navn populasjonsstørrelse arbeidsledighet
GB   England                 56.0            1.0%
IS    Island                  0.4            4.9%
SE   Sverige                 10.0            3.2%
DK   Danmark                    6            1.6%
DE  Tyskland                   83           12.5%
US       USA                  300             50%

### Oppg 6
Hva er gjennomsnittlig arbeidsledighet til landene over?

In [85]:
arbeids_ledighet = df_land["arbeidsledighet"]
arbeidsledighet_formatert = [float(s[:-1]) for s in arbeids_ledighet]
gjennomsnitt = sum(arbeidsledighet_formatert)/len(arbeidsledighet_formatert)
print(f"Gjennomsnittlig arbeidsledighet er {round(gjennomsnitt,1)}%")

Gjennomsnittlig arbeidsledighet er 12.2%