In [58]:
# TEST Metadata ssb
import requests
from pyjstat import pyjstat

tabell = "08484"
url = f"https://data.ssb.no/api/v0/no/table/{tabell}"
#url = f"https://data.ssb.no/api/v0/no/console/meta/table/{tabell}"
print(url)
respons = requests.get(url)

https://data.ssb.no/api/v0/no/table/08484

In [59]:
import pandas as pd
meta_data = respons.json()
variabler = meta_data["variables"]
"""
for var in variabler:
    print(var.keys())
    print("kode", var["text"])
    print("Verditekst", var["valueTexts"])

"""
meta_data2 = {"Variabelkode": variabler[0]["values"], "Variabelnavn": variabler[0]["valueTexts"]}


df = pd.DataFrame(data=meta_data2)
df

      Variabelkode                                       Variabelnavn
0    1AAAAA-9ZZZZz                              Alle lovbruddsgrupper
1    1AAAAA-1ZZZZz                                   ¬ Eiendomstyveri
2    2AAAAA-2ZZZZz                           ¬ Annet vinningslovbrudd
3    3AAAAA-3ZZZZz                                    ¬ Eiendomsskade
4    4AAAAA-4ZZZZz                              ¬ Vold og mishandling
5    5AAAAA-5ZZZZz                                  ¬ Seksuallovbrudd
6    6AAAAA-6ZZZZz                                ¬ Rusmiddellovbrudd
7    7AAAAA-7ZZZZz                  ¬ Ordens- og integritetskrenkelse
8    8AAAAA-8ZZZZz                              ¬ Trafikkovertredelse
9    9AAAAA-9ZZZZz                                   ¬ Annet lovbrudd
10   1AAAAA-9ZZZZZ                                Alle lovbruddstyper
11   1AAAAA-1ZZZZZ                                   ¬ Eiendomstyveri
12   1AAAAA-1AZZZZ                                   ¬¬ Tyveri, i alt
13   1AAAAA-1AAZZZ                                  ¬¬¬ Mindre tyveri
14          1AAAZZ   ¬¬¬¬ Mindre tyveri fra butikk og annet salgssted
15          1AAZZZ        ¬¬¬¬ Annet eller uspesifisert mindre tyveri
16   1ABAAA-1ABZZZ                                         ¬¬¬ Tyveri
17          1ABCZZ          ¬¬¬¬ Tyveri fra butikk og annet salgssted
18          1ABDZZ  ¬¬¬¬ Tyveri fra annen næring og offentlig virk...
19   1ABEAA-1ABEZZ              ¬¬¬¬ Tyveri fra bolig og fritidsbolig
20          1ABEAZ                             ¬¬¬¬¬ Tyveri fra bolig
21          1ABEBZ                      ¬¬¬¬¬ Tyveri fra fritidsbolig
22          1ABECZ  ¬¬¬¬¬ Tyveri fra bod, garasje og areal til bol...
23          1ABFZZ         ¬¬¬¬ Tyveri fra bil og annet motorkjøretøy
24          1ABGZZ                              ¬¬¬¬ Tyveri av sykkel
25   1ABHAA-1ABHZZ                             ¬¬¬¬ Tyveri fra person
26          1ABHAZ              ¬¬¬¬¬ Tyveri fra person i salgslokale
27          1ABHBZ  ¬¬¬¬¬ Tyveri fra person i kollektiv transport ...
28          1ABHCZ  ¬¬¬¬¬ Tyveri fra person i gate, park, annet fr...
29          1ABHDZ  ¬¬¬¬¬ Tyveri fra person i anlegg for idrett, k...
30          1ABHZZ  ¬¬¬¬¬ Tyveri fra person på annet offentlig og ...
31          1ABZZZ               ¬¬¬¬ Annet eller uspesifisert tyveri
32   1ACAAA-1ACZZZ                                   ¬¬¬ Grovt tyveri
33          1ACAZZ    ¬¬¬¬ Grovt tyveri fra butikk og annet salgssted
34          1ACBZZ  ¬¬¬¬ Grovt tyveri fra annen næring og offentli...
35   1ACCAA-1ACCZZ        ¬¬¬¬ Grovt tyveri fra bolig og fritidsbolig
36          1ACCAZ                       ¬¬¬¬¬ Grovt tyveri fra bolig
37          1ACCBZ                ¬¬¬¬¬ Grovt tyveri fra fritidsbolig
38          1ACCCZ  ¬¬¬¬¬ Grovt tyveri fra bod, garasje og areal t...
39          1ACDZZ   ¬¬¬¬ Grovt tyveri fra bil og annet motorkjøretøy
40   1ACEAA-1ACEZZ                       ¬¬¬¬ Grovt tyveri fra person
41          1ACEAZ  ¬¬¬¬¬ Grovt tyveri fra person i salgslokale (f...
42          1ACEBZ  ¬¬¬¬¬ Grovt tyveri fra person i kollektiv tran...
43          1ACECZ  ¬¬¬¬¬ Grovt tyveri fra person i gate, park, an...
44          1ACEDZ  ¬¬¬¬¬ Grovt tyveri fra person i anlegg for idr...
45          1ACEZZ  ¬¬¬¬¬ Grovt tyveri fra person på annet eller u...
46          1ACZZZ         ¬¬¬¬ Annet eller uspesifisert grovt tyveri
47   1ADAAA-1ADZZZ      ¬¬¬ Brukstyveri av bil og annet motorkjøretøy
48          1ADAZZ                            ¬¬¬¬ Brukstyveri av bil
49          1ADBZZ           ¬¬¬¬ Brukstyveri av motorsykkel og moped
50          1ADZZZ  ¬¬¬¬ Annet eller uspesifisert brukstyveri av m...
51          1BZZZZ      ¬¬ Annen bruk og besittelse av andres eiendel
52   2AAAAA-2ZZZZZ                           ¬ Annet vinningslovbrudd
53   2AAAAA-2AZZZZ                           ¬¬ Heleri og hvitvasking
54   2AAAAA-2AAZZZ                                  ¬¬¬ Heleri, i alt
55          2AAAZZ                                        ¬¬¬¬ Heleri
56          2AABZZ                                  ¬¬¬¬ Grovt heleri
57   2ABAAA-2ABZZZ                             ¬¬¬ Hvitvasking, i alt
58          2ABAZZ                                   ¬¬¬¬ Hvitvasking
59          2ABBZZ                              ¬¬¬¬ Grov hvitvasking
60          2AZZZZ  ¬¬¬ Annet eller uspesifisert heleri og hvitvas...
61   2BAAAA-2BZZZZ                                ¬¬ Bedrageri, i alt
62          2BAZZZ                   ¬¬¬ Mindre bedrageri og liknende
63          2BBZZZ                                      ¬¬¬ Bedrageri
64          2BCZZZ                                ¬¬¬ Grovt bedrageri
65   2CAAAA-2CZZZZ                                ¬¬ Underslag, i alt
66          2CAZZZ                                      ¬¬¬ Underslag
67          2CBZZZ                                ¬¬¬ Grovt underslag
68          2DZZZZ                              ¬¬ Økonomisk utroskap
69          2EZZZZ                 ¬¬ Korrupsjon og påvirkningshandel
70          2FZZZZ                           ¬¬ Regnskapsovertredelse
71          2GZZZZ                       ¬¬ Kreditorrelatert lovbrudd
72   2HAAAA-2HZZZZ                                 ¬¬ Skatt og avgift
73          2HAZZZ                                     ¬¬¬ Skattesvik
74          2HBZZZ                               ¬¬¬ Grovt skattesvik
75          2HZZZZ                         ¬¬¬ Annet, skatt og avgift
76   2IAAAA-2IZZZZ                                        ¬¬ Tolloven
77          2IAZZZ                                       ¬¬¬ Smugling
78          2IZZZZ                                ¬¬¬ Annet, tolloven
79          2ZZZZZ           ¬¬ Annet næringslivs- og økonomilovbrudd
80   3AAAAA-3ZZZZZ                                    ¬ Eiendomsskade
81   3AAAAA-3AZZZZ                                ¬¬ Skadeverk, i alt
82   3AAAAA-3AAZZZ                               ¬¬¬ Mindre skadeverk
83          3AAAZZ              ¬¬¬¬ Mindre skadeverk på og i bygning
84          3AABZZ  ¬¬¬¬ Mindre skadeverk på motorkjøretøy og anne...
85          3AAZZZ     ¬¬¬¬ Annet eller uspesifisert mindre skadeverk
86   3ABAAA-3ABZZZ                                      ¬¬¬ Skadeverk
87          3ABAZZ                     ¬¬¬¬ Skadeverk på og i bygning
88          3ABBZZ  ¬¬¬¬ Skadeverk på motorkjøretøy og annet trans...
89          3ABZZZ            ¬¬¬¬ Annet eller uspesifisert skadeverk
90   3ACAAA-3ACZZZ                                ¬¬¬ Grovt skadeverk
91          3ACAZZ               ¬¬¬¬ Grovt skadeverk på og i bygning
92          3ACBZZ  ¬¬¬¬ Grovt skadeverk på motorkjøretøy og annet...
93          3ACZZZ                         ¬¬¬¬ Annet grovt skadeverk
94          3BZZZZ  ¬¬ Fare for allmennheten ved brann og annen skade
95   4AAAAA-4ZZZZZ                              ¬ Vold og mishandling
96   4AAAAA-4AZZZZ                                   ¬¬ Voldslovbrudd
97   4AAAAA-4AAZZZ                         ¬¬¬ Kroppskrenkelse, i alt
98          4AAAZZ                               ¬¬¬¬ Kroppskrenkelse
99          4AABZZ                          ¬¬¬¬ Grov kroppskrenkelse
100  4ABAAA-4ABZZZ                             ¬¬¬ Kroppsskade, i alt
101         4ABAZZ                                   ¬¬¬¬ Kroppsskade
102         4ABBZZ                              ¬¬¬¬ Grov kroppsskade
103         4ACZZZ                                           ¬¬¬ Drap
104         4ADZZZ                                   ¬¬¬ Drap, forsøk
105  4AEAAA-4AEZZZ      ¬¬¬ Uaktsomt påført betydelig skade eller død
106         4AEAZZ                           ¬¬¬¬ Uaktsom kroppsskade
107         4AEBZZ                    ¬¬¬¬ Uaktsom forvoldelse av død
108  4AFAAA-4AFZZZ           ¬¬¬ Mishandling i nære relasjoner, i alt
109         4AFAZZ                 ¬¬¬¬ Mishandling i nære relasjoner
110         4AFBZZ            ¬¬¬¬ Grov mishandling i nære relasjoner
111         4AGZZZ              ¬¬¬ Vold mot offentlig tjenesteperson
112         4AZZZZ         ¬¬¬ Annet eller uspesifisert voldslovbrudd
113  4BAAAA-4BZZZZ                                  ¬¬ Trusler, i alt
114         4BAZZZ                        ¬¬¬ Trusler (fra 1.10.2015)
115         4BBZZZ                  ¬¬¬ Grove trusler (fra 1.10.2015)
116         4BCZZZ           ¬¬¬ Trusler mot offentlig tjenesteperson
117         4BZZZZ              ¬¬¬ Andre eller uspesifiserte trusler
118  4CAAAA-4CZZZZ                               ¬¬ Ran og utpressing
119         4CAZZZ                                            ¬¬¬ Ran
120         4CBZZZ                                      ¬¬¬ Grovt ran
121         4CCZZZ                                     ¬¬¬ Utpressing
122         4CZZZZ     ¬¬¬ Annet eller uspesifisert ran og utpressing
123         4DZZZZ                                           ¬¬ Tvang
124         4EZZZZ                                ¬¬ Frihetsberøvelse
125         4FZZZZ                      ¬¬ Omsorgs- og familieforhold
126         4GZZZZ          ¬¬ Hensynsløs atferd og personforfølgelse
127         4HZZZZ                                  ¬¬ Menneskehandel
128         4IZZZZ               ¬¬ Terror og terrorrelatert handling
129         4ZZZZZ                       ¬¬ Annen vold og mishandling
130  5AAAAA-5ZZZZZ                                  ¬ Seksuallovbrudd
131  5AAAAA-5AZZZZ                                 ¬¬ Voldtekt, i alt
132  5AAAAA-5AAZZZ                                       ¬¬¬ Voldtekt
133         5AAAZZ                    ¬¬¬¬ Voldtekt, barn under 14 år
134         5AAZZZ      ¬¬¬¬ Voldtekt, annen eller uspesifisert alder
135  5ABAAA-5ABZZZ                                  ¬¬¬ Grov voldtekt
136         5ABAZZ  ¬¬¬¬ Grov voldtekt, barn under 14 år (fra 1.10...
137         5ABZZZ  ¬¬¬¬ Grov voldtekt, annen eller uspesifisert a...
138         5BZZZZ                                ¬¬ Voldtekt, forsøk
139         5CZZZZ              ¬¬ Seksuell omgang i overmaktsforhold
140         5DZZZZ                  ¬¬ Seksuell omgang, barn 14-15 år
141         5EZZZZ               ¬¬ Seksuell omgang mellom nærstående
142  5FAAAA-5FZZZZ                               ¬¬ Seksuell handling
143         5FAZZZ            ¬¬¬ Seksuell handling, barn under 16 år
144         5FZZZZ          ¬¬¬ Annen seksuell handling uten samtykke
145  5GAAAA-5GZZZZ                       ¬¬ Seksuelt krenkende atferd
146         5GAZZZ  ¬¬¬ Seksuelt krenkende atferd, barn under 16 å...
147         5GZZZZ  ¬¬¬ Seksuelt krenkende atferd, annen eller usp...
148         5ZZZZZ        ¬¬ Annet eller uspesifisert seksuallovbrudd
149  6AAAAA-6ZZZZZ                                ¬ Rusmiddellovbrudd
150  6AAAAA-6AZZZZ                               ¬¬ Narkotikalovbrudd
151  6AAAAA-6AAZZZ                     ¬¬¬ Narkotika, legemiddelloven
152         6AAAZZ                               ¬¬¬¬ Narkotika, bruk
153         6AABZZ                  ¬¬¬¬ Narkotika, mindre besittelse
154  6ABAAA-6ABZZZ                 ¬¬¬ Narkotika, straffeloven, i alt
155         6ABAZZ           ¬¬¬¬ Narkotikaovertredelse, straffeloven
156         6ABBZZ      ¬¬¬¬ Grov narkotikaovertredelse, straffeloven
157  6BAAAA-6BZZZZ                                          ¬¬ Doping
158         6BAZZZ                        ¬¬¬ Doping, legemiddelloven
159         6BBZZZ                           ¬¬¬ Doping, straffeloven
160  6CAAAA-6CZZZZ                             ¬¬ Ruspåvirket kjøring
161         6CAZZZ                    ¬¬¬ Promillekjøring, veitrafikk
162         6CZZZZ                         ¬¬¬ Promillekjøring, annet
163  6DAAAA-6DZZZZ                   ¬¬ Alkohollovovertredelse, i alt
164         6DAZZZ                         ¬¬¬ Alkohollovovertredelse
165         6DBZZZ                    ¬¬¬ Grov alkohollovovertredelse
166         6ZZZZZ      ¬¬ Annet eller uspesifisert rusmiddellovbrudd
167  7AAAAA-7ZZZZZ                  ¬ Ordens- og integritetskrenkelse
168  7AAAAA-7ABZZZ                       ¬¬ Offentlig ordenskrenkelse
169  7AAAAA-7AAZZZ                      ¬¬¬ Ordensforstyrrelse, i alt
170         7AAAZZ    ¬¬¬¬ Regional ordensvedtekt, urinering og annet
171         7AABZZ        ¬¬¬¬ Ordensforstyrrelse i selvforskyldt rus
172         7AAZZZ   ¬¬¬¬ Annen eller uspesifisert ordensforstyrrelse
173  7ABAAA-7ABZZZ          ¬¬¬ Våpen-, brann- og eksplosivlovgivning
174         7ABAZZ                   ¬¬¬¬ Bevæpning på offentlig sted
175         7ABBZZ        ¬¬¬¬ Annet eller uspesifisert våpenlovbrudd
176         7ABCZZ                 ¬¬¬¬ Brann- og eksplosivlovgivning
177  7BAAAA-7BZZZZ                             ¬¬ Myndighetskrenkelse
178  7BAAAA-7BAZZZ       ¬¬¬ Hindre og motarbeide offentlig myndighet
179  7BAAAA-7BAAZZ  ¬¬¬¬ Hindre og forulempe offentlig tjenesteperson
180         7BAAAZ           ¬¬¬¬¬ Forulempe offentlig tjenesteperson
181         7BAABZ              ¬¬¬¬¬ Hindre offentlig tjenesteperson
182  7BABAA-7BABZZ       ¬¬¬¬ Motarbeide retts- og straffeforfølgning
183         7BABAZ  ¬¬¬¬¬ Identifikasjonsplikt overfor offentlig m...
184         7BABBZ                   ¬¬¬¬¬ Oppholds- og kontaktforbud
185         7BABCZ   ¬¬¬¬¬ Annet pålegg fra politi og annen myndighet
186         7BABDZ              ¬¬¬¬¬ Motarbeide straffegjennomføring
187         7BABZZ  ¬¬¬¬¬ Annet, motarbeide retts- og straffeforfø...
188  7BBAAA-7BBZZZ                  ¬¬¬ Uriktig forklaring og anklage
189         7BBAZZ                            ¬¬¬¬ Uriktig forklaring
190         7BBBZZ                               ¬¬¬¬ Uriktig anklage
191  7BCAAA-7BCZZZ                           ¬¬¬ Utlendingslovgivning
192         7BCAZZ                                ¬¬¬¬ Innreiseforbud
193         7BCBZZ             ¬¬¬¬ Bistå ulovlig innreise og opphold
194         7BCZZZ  ¬¬¬¬ Annen eller uspesifisert utlendingslovgiv...
195         7BDZZZ  ¬¬¬ Tjenestefeil og misbruk av offentlig myndi...
196         7BZZZZ   ¬¬¬ Annen eller uspesifisert myndighetskrenkelse
197  7CAAAA-7CZZZZ                            ¬¬ Integritetskrenkelse
198  7CAAAA-7CAZZZ                      ¬¬¬ Dokument- og ID-krenkelse
199  7CAAAA-7CAAZZ                                 ¬¬¬¬ Dokumentfalsk
200         7CAAAZ                          ¬¬¬¬¬ Dokumentfalsk, bruk
201         7CAABZ        ¬¬¬¬¬ Dokumentfalsk, tilvirket og anskaffet
202         7CABZZ                                    ¬¬¬¬ Pengefalsk
203  7CACAA-7CACZZ                  ¬¬¬¬ ID-krenkelse (fra 1.10.2015)
204         7CACAZ      ¬¬¬¬¬ ID-krenkelse, befatning (fra 1.10.2015)
205         7CACBZ           ¬¬¬¬¬ ID-krenkelse, bruk (fra 1.10.2015)
206         7CAZZZ  ¬¬¬¬ Annen eller uspesifisert dokument- og ID-...
207  7CBAAA-7CBZZZ                  ¬¬¬ Uberettiget adgang og opphold
208         7CBAZZ          ¬¬¬¬ Inntrengning i bygning og annet sted
209         7CBBZZ  ¬¬¬¬ Inntrengning i data- og kommunikasjonssystem
210         7CCZZZ       ¬¬¬ Offentlig krenkelse av privatlivets fred
211         7CDZZZ           ¬¬¬ Hatefulle ytringer og diskriminering
212         7CZZZZ  ¬¬¬ Annen eller uspesifisert integritetskrenkelse
213  8AAAAA-8ZZZZZ                              ¬ Trafikkovertredelse
214  8AAAAA-8AZZZZ                          ¬¬ Veitrafikkovertredelse
215         8AAZZZ                          ¬¬¬ Uten gyldig førerkort
216         8ABZZZ                              ¬¬¬ Ulovlig hastighet
217         8ACZZZ                                    ¬¬¬ Personskade
218         8AZZZZ  ¬¬¬ Annen eller uspesifisert veitrafikkovertre...
219         8ZZZZZ           ¬¬ Annen transport- og trafikklovgivning
220  9AAAAA-9ZZZZZ                                   ¬ Annet lovbrudd
221  9AAAAA-9AZZZZ                         ¬¬ Natur- og miljølovbrudd
222         9AAZZZ  ¬¬¬ Allmennfarlig forgiftning og alvorlig milj...
223         9ABZZZ              ¬¬¬ Jakt-, fangst- og fiskerilovbrudd
224         9AZZZZ                  ¬¬¬ Annet natur- og miljølovbrudd
225         9BZZZZ                          ¬¬ Arbeidsmiljølovgivning
226         9ZZZZZ      ¬¬ Annen eller uspesifisert straffelovgivning
227          0-999                                              I alt
228              1                                       Forbrytelser
229              0                                         Forseelser
230             01                              Alle lovbruddsgrupper
231             10                             Økonomisk kriminalitet
232             11                         Annen vinningskriminalitet
233             12                                  Voldskriminalitet
234             13                                Seksualkriminalitet
235             14                              Narkotikakriminalitet
236             15                                          Skadeverk
237             16                                  Miljøkriminalitet
238             17                           Arbeidsmiljøkriminalitet
239             18                                 Trafikkriminalitet
240             19                                 Annen kriminalitet
241    AAAAA-ZZZZZ                                Alle typer lovbrudd
242    AAAAA-AZZZZ                                     ¬ Forbrytelser
243    AAAAA-AAZZZ                    ¬¬ Forbrytelse mot straffeloven
244          AAAZZ  ¬¬¬ Forbrytelse mot statens selvstendighet og ...
245    AABAA-AABZZ  ¬¬¬ Forbrytelse mot Norges statsforfatning og ...
246          AABAZ                  ¬¬¬¬ Forbrytelse mot statsmaktene
247          AABZZ  ¬¬¬¬ Annet, forbrytelse mot Norges statsforfat...
248          AACZZ  ¬¬¬ Forbrytelse mht. utøvelse av statsborgerli...
249    AADAA-AADZZ          ¬¬¬ Forbrytelse i den offentlige tjeneste
250          AADAZ  ¬¬¬¬ Vinningsforbrytelse i den offentlig tjeneste
251          AADBZ                ¬¬¬¬ Brevbrudd (offentlig tjeneste)
252          AADCZ                          ¬¬¬¬ Misbruk av myndighet
253          AADZZ  ¬¬¬¬ Annet, forbrytelse i den offentlige tjeneste
254    AAEAA-AAEZZ       ¬¬¬ Forbrytelse mot den offentlige myndighet
255          AAEAZ               ¬¬¬¬ Vold mot offentlig tjenestemann
256          AAEBZ  ¬¬¬¬ Ulovlig påvirkning av offentlig tjenestemann
257          AAECZ  ¬¬¬¬ Motarbeiding av etterforskning, medvirkni...
258          AAEZZ  ¬¬¬¬ Annet, forbrytelse mot den offentlige myn...
259    AAFAA-AAFZZ  ¬¬¬ Forbrytelse mot den alminnelige orden og fred
260          AAFAZ                          ¬¬¬¬ Opprør og oppløp mv.
261          AAFBZ                            ¬¬¬¬ Rasediskriminering
262          AAFCZ        ¬¬¬¬ Oppfordring til straffbar handling mv.
263          AAFDZ                     ¬¬¬¬ Brevbrudd (orden og fred)
264          AAFEZ                                      ¬¬¬¬ Innbrudd
265          AAFZZ  ¬¬¬¬ Annet, forbrytelse mot den alminnelige or...
266    AAGAA-AAGZZ                      ¬¬¬ Allmennfarlig forbrytelse
267          AAGAZ           ¬¬¬¬ Forsettlig forvoldelse av ildebrann
268          AAGBZ              ¬¬¬¬ Uaktsom forvoldelse av ildebrann
269          AAGCZ           ¬¬¬¬ Narkotikaforbrytelse (straffeloven)
270          AAGDZ      ¬¬¬¬ Grov narkotikaforbrytelse (straffeloven)
271          AAGZZ              ¬¬¬¬ Annet, allmennfarlig forbrytelse
272          AAHAZ                               ¬¬¬ Falsk forklaring
273    AAIAA-AAIZZ                                  ¬¬¬ Falsk anklage
274          AAIAZ                      ¬¬¬¬ Forsettlig falsk anklage
275          AAIZZ                          ¬¬¬¬ Annet, falsk anklage
276          AAJAZ                                     ¬¬¬ Pengefalsk
277    AAKAA-AAKZZ                                  ¬¬¬ Dokumentfalsk
278          AAKAZ                 ¬¬¬¬ Benyttelse av falskt dokument
279          AAKBZ                      ¬¬¬¬ Forfalskning av dokument
280          AAKZZ                          ¬¬¬¬ Annet, dokumentfalsk
281    AALAA-AALZZ                            ¬¬¬ Seksualforbrytelser
282          AALAZ                                      ¬¬¬¬ Voldtekt
283          AALBZ  ¬¬¬¬ Seksuell omgang m/trusler, underfundig ad...

In [60]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
items = df.query("Variabelnavn.str.contains('tyveri', case=False)")["Variabelkode"].values

In [61]:
meta_data

{'title': '08484: Anmeldte lovbrudd, etter lovbruddstype, statistikkvariabel og år',
 'variables': [{'code': 'LovbruddKrim',
   'text': 'lovbruddstype',
   'values': ['1AAAAA-9ZZZZz',
    '1AAAAA-1ZZZZz',
    '2AAAAA-2ZZZZz',
    '3AAAAA-3ZZZZz',
    '4AAAAA-4ZZZZz',
    '5AAAAA-5ZZZZz',
    '6AAAAA-6ZZZZz',
    '7AAAAA-7ZZZZz',
    '8AAAAA-8ZZZZz',
    '9AAAAA-9ZZZZz',
    '1AAAAA-9ZZZZZ',
    '1AAAAA-1ZZZZZ',
    '1AAAAA-1AZZZZ',
    '1AAAAA-1AAZZZ',
    '1AAAZZ',
    '1AAZZZ',
    '1ABAAA-1ABZZZ',
    '1ABCZZ',
    '1ABDZZ',
    '1ABEAA-1ABEZZ',
    '1ABEAZ',
    '1ABEBZ',
    '1ABECZ',
    '1ABFZZ',
    '1ABGZZ',
    '1ABHAA-1ABHZZ',
    '1ABHAZ',
    '1ABHBZ',
    '1ABHCZ',
    '1ABHDZ',
    '1ABHZZ',
    '1ABZZZ',
    '1ACAAA-1ACZZZ',
    '1ACAZZ',
    '1ACBZZ',
    '1ACCAA-1ACCZZ',
    '1ACCAZ',
    '1ACCBZ',
    '1ACCCZ',
    '1ACDZZ',
    '1ACEAA-1ACEZZ',
    '1ACEAZ',
    '1ACEBZ',
    '1ACECZ',
    '1ACEDZ',
    '1ACEZZ',
    '1ACZZZ',
    '1ADAAA-1ADZZZ',
    '1ADAZZ',
    '1ADBZZ',
    '1ADZZZ',
    '1BZZZZ',
    '2AAAAA-2ZZZZZ',
    '2AAAAA-2AZZZZ',
    '2AAAAA-2AAZZZ',
    '2AAAZZ',
    '2AABZZ',
    '2ABAAA-2ABZZZ',
    '2ABAZZ',
    '2ABBZZ',
    '2AZZZZ',
    '2BAAAA-2BZZZZ',
    '2BAZZZ',
    '2BBZZZ',
    '2BCZZZ',
    '2CAAAA-2CZZZZ',
    '2CAZZZ',
    '2CBZZZ',
    '2DZZZZ',
    '2EZZZZ',
    '2FZZZZ',
    '2GZZZZ',
    '2HAAAA-2HZZZZ',
    '2HAZZZ',
    '2HBZZZ',
    '2HZZZZ',
    '2IAAAA-2IZZZZ',
    '2IAZZZ',
    '2IZZZZ',
    '2ZZZZZ',
    '3AAAAA-3ZZZZZ',
    '3AAAAA-3AZZZZ',
    '3AAAAA-3AAZZZ',
    '3AAAZZ',
    '3AABZZ',
    '3AAZZZ',
    '3ABAAA-3ABZZZ',
    '3ABAZZ',
    '3ABBZZ',
    '3ABZZZ',
    '3ACAAA-3ACZZZ',
    '3ACAZZ',
    '3ACBZZ',
    '3ACZZZ',
    '3BZZZZ',
    '4AAAAA-4ZZZZZ',
    '4AAAAA-4AZZZZ',
    '4AAAAA-4AAZZZ',
    '4AAAZZ',
    '4AABZZ',
    '4ABAAA-4ABZZZ',
    '4ABAZZ',
    '4ABBZZ',
    '4ACZZZ',
    '4ADZZZ',
    '4AEAAA-4AEZZZ',
    '4AEAZZ',
    '4AEBZZ',
    '4AFAAA-4AFZZZ',
    '4AFAZZ',
    '4AFBZZ',
    '4AGZZZ',
    '4AZZZZ',
    '4BAAAA-4BZZZZ',
    '4BAZZZ',
    '4BBZZZ',
    '4BCZZZ',
    '4BZZZZ',
    '4CAAAA-4CZZZZ',
    '4CAZZZ',
    '4CBZZZ',
    '4CCZZZ',
    '4CZZZZ',
    '4DZZZZ',
    '4EZZZZ',
    '4FZZZZ',
    '4GZZZZ',
    '4HZZZZ',
    '4IZZZZ',
    '4ZZZZZ',
    '5AAAAA-5ZZZZZ',
    '5AAAAA-5AZZZZ',
    '5AAAAA-5AAZZZ',
    '5AAAZZ',
    '5AAZZZ',
    '5ABAAA-5ABZZZ',
    '5ABAZZ',
    '5ABZZZ',
    '5BZZZZ',
    '5CZZZZ',
    '5DZZZZ',
    '5EZZZZ',
    '5FAAAA-5FZZZZ',
    '5FAZZZ',
    '5FZZZZ',
    '5GAAAA-5GZZZZ',
    '5GAZZZ',
    '5GZZZZ',
    '5ZZZZZ',
    '6AAAAA-6ZZZZZ',
    '6AAAAA-6AZZZZ',
    '6AAAAA-6AAZZZ',
    '6AAAZZ',
    '6AABZZ',
    '6ABAAA-6ABZZZ',
    '6ABAZZ',
    '6ABBZZ',
    '6BAAAA-6BZZZZ',
    '6BAZZZ',
    '6BBZZZ',
    '6CAAAA-6CZZZZ',
    '6CAZZZ',
    '6CZZZZ',
    '6DAAAA-6DZZZZ',
    '6DAZZZ',
    '6DBZZZ',
    '6ZZZZZ',
    '7AAAAA-7ZZZZZ',
    '7AAAAA-7ABZZZ',
    '7AAAAA-7AAZZZ',
    '7AAAZZ',
    '7AABZZ',
    '7AAZZZ',
    '7ABAAA-7ABZZZ',
    '7ABAZZ',
    '7ABBZZ',
    '7ABCZZ',
    '7BAAAA-7BZZZZ',
    '7BAAAA-7BAZZZ',
    '7BAAAA-7BAAZZ',
    '7BAAAZ',
    '7BAABZ',
    '7BABAA-7BABZZ',
    '7BABAZ',
    '7BABBZ',
    '7BABCZ',
    '7BABDZ',
    '7BABZZ',
    '7BBAAA-7BBZZZ',
    '7BBAZZ',
    '7BBBZZ',
    '7BCAAA-7BCZZZ',
    '7BCAZZ',
    '7BCBZZ',
    '7BCZZZ',
    '7BDZZZ',
    '7BZZZZ',
    '7CAAAA-7CZZZZ',
    '7CAAAA-7CAZZZ',
    '7CAAAA-7CAAZZ',
    '7CAAAZ',
    '7CAABZ',
    '7CABZZ',
    '7CACAA-7CACZZ',
    '7CACAZ',
    '7CACBZ',
    '7CAZZZ',
    '7CBAAA-7CBZZZ',
    '7CBAZZ',
    '7CBBZZ',
    '7CCZZZ',
    '7CDZZZ',
    '7CZZZZ',
    '8AAAAA-8ZZZZZ',
    '8AAAAA-8AZZZZ',
    '8AAZZZ',
    '8ABZZZ',
    '8ACZZZ',
    '8AZZZZ',
    '8ZZZZZ',
    '9AAAAA-9ZZZZZ',
    '9AAAAA-9AZZZZ',
    '9AAZZZ',
    '9ABZZZ',
    '9AZZZZ',
    '9BZZZZ',
    '9ZZZZZ',
    '0-999',
    '1',
    '0',
    '01',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    'AAAAA-ZZZZZ',
    'AAAAA-AZZZZ',
    'AAAAA-AAZZZ',
    'AAAZZ',
    'AABAA-AABZZ',
    'AABAZ',
    'AABZZ',
    'AACZZ',
    'AADAA-AADZZ',
    'AADAZ',
    'AADBZ',
    'AADCZ',
    'AADZZ',
    'AAEAA-AAEZZ',
    'AAEAZ',
    'AAEBZ',
    'AAECZ',
    'AAEZZ',
    'AAFAA-AAFZZ',
    'AAFAZ',
    'AAFBZ',
    'AAFCZ',
    'AAFDZ',
    'AAFEZ',
    'AAFZZ',
    'AAGAA-AAGZZ',
    'AAGAZ',
    'AAGBZ',
    'AAGCZ',
    'AAGDZ',
    'AAGZZ',
    'AAHAZ',
    'AAIAA-AAIZZ',
    'AAIAZ',
    'AAIZZ',
    'AAJAZ',
    'AAKAA-AAKZZ',
    'AAKAZ',
    'AAKBZ',
    'AAKZZ',
    'AALAA-AALZZ',
    'AALAZ',
    'AALBZ',
    'AALCZ',
    'AALDZ',
    'AALEZ',
    'AALFA-AALFZ',
    'AALFA',
    'AALFB',
    'AALFC',
    'AALGZ',
    'AALHZ',
    'AALIZ',
    'AALKZ',
    'AALZZ',
    'AAMAA-AAMZZ',
    'AAMAZ',
    'AAMBZ',
    'AAMCZ',
    'AAMDZ',
    'AAMEZ',
    'AAMZZ',
    'AANAA-AANZZ',
    'AANAZ',
    'AANBZ',
    'AANZZ',
    'AAOAA-AAOZZ',
    'AAOAZ',
    'AAOBZ',
    'AAOCZ',
    'AAODZ',
    'AAOEZ',
    'AAOFZ',
    'AAOGZ',
    'AAOZZ',
    'AAPAZ',
    'AAQAA-AAQZZ',
    'AAQAZ',
    'AAQBZ',
    'AARAA-AARZZ',
    'AARAA-AARAZ',
    'AARAA',
    'AARAB',
    'AARAC',
    'AARAD',
    'AARAE',
    'AARAF',
    'AARAG',
    'AARAH',
    'AARAI',
    'AARAZ',
    'AARBA-AARBZ',
    'AARBA',
    'AARBB',
    'AARBC',
    'AARBD',
    'AARBE',
    'AARBZ',
    'AARCA-AARCZ',
    'AARCA',
    'AARCB',
    'AARCZ',
    'AASAA-AASZZ',
    'AASAZ',
    'AASBZ',
    'AASCZ',
    'AASZZ',
    'AATAA-AATZZ',
    'AATAZ',
    'AATBZ',
    'AATCZ',
    'AATDZ',
    'AATEZ',
    'AATFZ',
    'AATZZ',
    'AAUAA-AAUZZ',
    'AAUAZ',
    'AAUZZ',
    'AAVAA-AAVZZ',
    'AAVAZ',
    'AAVBZ',
    'AAVCZ',
    'AAWZZ',
    'AAXZZ',
    'AAYAA-AAYZZ',
    'AAYAZ',
    'AAYBZ',
    'AAYZZ',
    'ABAAA-ABZZZ',
    'ABAZZ',
    'ABBZZ',
    'ABZZZ',
    'ACZZZ',
    'ADZZZ',
    'AEAAA-AEZZZ',
    'AEAZZ',
    'AEBZZ',
    'AEZZZ',
    'AFAAA-AFZZZ',
    'AFAZZ',
    'AFZZZ',
    'AGAAA-AGZZZ',
    'AGAZZ',
    'AGBZZ',
    'AGZZZ',
    'AZZZZ',
    'BAAAA-BZZZZ',
    'BAAAA-BAZZZ',
    'BAAZZ',
    'BABZZ',
    'BACZZ',
    'BADZZ',
    'BAEZZ',
    'BAZZZ',
    'BBAAA-BBZZZ',
    'BBAZZ',
    'BBBZZ',
    'BBCZZ',
    'BBDZZ',
    'BBZZZ',
    'BCAAA-BCZZZ',
    'BCAZZ',
    'BCBZZ',
    'BCZZZ',
    'BDAAA-BDZZZ',
    'BDAZZ',
    'BDBZZ',
    'BDZZZ',
    'BEZZZ',
    'BFZZZ',
    'BGAAA-BGZZZ',
    'BGAZZ',
    'BGBZZ',
    'BGZZZ',
    'BHAAA-BHZZZ',
    'BHAZZ',
    'BHBZZ',
    'BHZZZ',
    'BIZZZ',
    'BZZZZ'],
   'valueTexts': ['Alle lovbruddsgrupper',
    '¬ Eiendomstyveri',
    '¬ Annet vinningslovbrudd',
    '¬ Eiendomsskade',
    '¬ Vold og mishandling',
    '¬ Seksuallovbrudd',
    '¬ Rusmiddellovbrudd',
    '¬ Ordens- og integritetskrenkelse',
    '¬ Trafikkovertredelse',
    '¬ Annet lovbrudd',
    'Alle lovbruddstyper',
    '¬ Eiendomstyveri',
    '¬¬ Tyveri, i alt',
    '¬¬¬ Mindre tyveri',
    '¬¬¬¬ Mindre tyveri fra butikk og annet salgssted',
    '¬¬¬¬ Annet eller uspesifisert mindre tyveri',
    '¬¬¬ Tyveri',
    '¬¬¬¬ Tyveri fra butikk og annet salgssted',
    '¬¬¬¬ Tyveri fra annen næring og offentlig virksomhet',
    '¬¬¬¬ Tyveri fra bolig og fritidsbolig',
    '¬¬¬¬¬ Tyveri fra bolig',
    '¬¬¬¬¬ Tyveri fra fritidsbolig',
    '¬¬¬¬¬ Tyveri fra bod, garasje og areal til bolig og fritidsbolig',
    '¬¬¬¬ Tyveri fra bil og annet motorkjøretøy',
    '¬¬¬¬ Tyveri av sykkel',
    '¬¬¬¬ Tyveri fra person',
    '¬¬¬¬¬ Tyveri fra person i salgslokale',
    '¬¬¬¬¬ Tyveri fra person i kollektiv transport (fra 1.10.2015)',
    '¬¬¬¬¬ Tyveri fra person i gate, park, annet friområde (fra 1.10.2015)',
    '¬¬¬¬¬ Tyveri fra person i anlegg for idrett, kultur o.l. (fra 1.10.2015)',
    '¬¬¬¬¬ Tyveri fra person på annet offentlig og privat sted (fra 1.10.2015)',
    '¬¬¬¬ Annet eller uspesifisert tyveri',
    '¬¬¬ Grovt tyveri',
    '¬¬¬¬ Grovt tyveri fra butikk og annet salgssted',
    '¬¬¬¬ Grovt tyveri fra annen næring og offentlig virksomhet',
    '¬¬¬¬ Grovt tyveri fra bolig og fritidsbolig',
    '¬¬¬¬¬ Grovt tyveri fra bolig',
    '¬¬¬¬¬ Grovt tyveri fra fritidsbolig',
    '¬¬¬¬¬ Grovt tyveri fra bod, garasje og areal til bolig og fritidsbolig',
    '¬¬¬¬ Grovt tyveri fra bil og annet motorkjøretøy',
    '¬¬¬¬ Grovt tyveri fra person',
    '¬¬¬¬¬ Grovt tyveri fra person i salgslokale (fra 1.10.2015)',
    '¬¬¬¬¬ Grovt tyveri fra person i kollektiv transport (fra 1.10.2015)',
    '¬¬¬¬¬ Grovt tyveri fra person i gate, park, annet friområde (fra 1.10.2015)',
    '¬¬¬¬¬ Grovt tyveri fra person i anlegg for idrett, kultur o.l. (fra 1.10.2015)',
    '¬¬¬¬¬ Grovt tyveri fra person på annet eller uspesifisert sted',
    '¬¬¬¬ Annet eller uspesifisert grovt tyveri',
    '¬¬¬ Brukstyveri av bil og annet motorkjøretøy',
    '¬¬¬¬ Brukstyveri av bil',
    '¬¬¬¬ Brukstyveri av motorsykkel og moped',
    '¬¬¬¬ Annet eller uspesifisert brukstyveri av motorkjøretøy',
    '¬¬ Annen bruk og besittelse av andres eiendel',
    '¬ Annet vinningslovbrudd',
    '¬¬ Heleri og hvitvasking',
    '¬¬¬ Heleri, i alt',
    '¬¬¬¬ Heleri',
    '¬¬¬¬ Grovt heleri',
    '¬¬¬ Hvitvasking, i alt',
    '¬¬¬¬ Hvitvasking',
    '¬¬¬¬ Grov hvitvasking',
    '¬¬¬ Annet eller uspesifisert heleri og hvitvasking',
    '¬¬ Bedrageri, i alt',
    '¬¬¬ Mindre bedrageri og liknende',
    '¬¬¬ Bedrageri',
    '¬¬¬ Grovt bedrageri',
    '¬¬ Underslag, i alt',
    '¬¬¬ Underslag',
    '¬¬¬ Grovt underslag',
    '¬¬ Økonomisk utroskap',
    '¬¬ Korrupsjon og påvirkningshandel',
    '¬¬ Regnskapsovertredelse',
    '¬¬ Kreditorrelatert lovbrudd',
    '¬¬ Skatt og avgift',
    '¬¬¬ Skattesvik',
    '¬¬¬ Grovt skattesvik',
    '¬¬¬ Annet, skatt og avgift',
    '¬¬ Tolloven',
    '¬¬¬ Smugling',
    '¬¬¬ Annet, tolloven',
    '¬¬ Annet næringslivs- og økonomilovbrudd',
    '¬ Eiendomsskade',
    '¬¬ Skadeverk, i alt',
    '¬¬¬ Mindre skadeverk',
    '¬¬¬¬ Mindre skadeverk på og i bygning',
    '¬¬¬¬ Mindre skadeverk på motorkjøretøy og annet transportmiddel (fra 1.10.2015)',
    '¬¬¬¬ Annet eller uspesifisert mindre skadeverk',
    '¬¬¬ Skadeverk',
    '¬¬¬¬ Skadeverk på og i bygning',
    '¬¬¬¬ Skadeverk på motorkjøretøy og annet transportmiddel',
    '¬¬¬¬ Annet eller uspesifisert skadeverk',
    '¬¬¬ Grovt skadeverk',
    '¬¬¬¬ Grovt skadeverk på og i bygning',
    '¬¬¬¬ Grovt skadeverk på motorkjøretøy og annet transportmiddel',
    '¬¬¬¬ Annet grovt skadeverk',
    '¬¬ Fare for allmennheten ved brann og annen skade',
    '¬ Vold og mishandling',
    '¬¬ Voldslovbrudd',
    '¬¬¬ Kroppskrenkelse, i alt',
    '¬¬¬¬ Kroppskrenkelse',
    '¬¬¬¬ Grov kroppskrenkelse',
    '¬¬¬ Kroppsskade, i alt',
    '¬¬¬¬ Kroppsskade',
    '¬¬¬¬ Grov kroppsskade',
    '¬¬¬ Drap',
    '¬¬¬ Drap, forsøk',
    '¬¬¬ Uaktsomt påført betydelig skade eller død',
    '¬¬¬¬ Uaktsom kroppsskade',
    '¬¬¬¬ Uaktsom forvoldelse av død',
    '¬¬¬ Mishandling i nære relasjoner, i alt',
    '¬¬¬¬ Mishandling i nære relasjoner',
    '¬¬¬¬ Grov mishandling i nære relasjoner',
    '¬¬¬ Vold mot offentlig tjenesteperson',
    '¬¬¬ Annet eller uspesifisert voldslovbrudd',
    '¬¬ Trusler, i alt',
    '¬¬¬ Trusler (fra 1.10.2015)',
    '¬¬¬ Grove trusler (fra 1.10.2015)',
    '¬¬¬ Trusler mot offentlig tjenesteperson',
    '¬¬¬ Andre eller uspesifiserte trusler',
    '¬¬ Ran og utpressing',
    '¬¬¬ Ran',
    '¬¬¬ Grovt ran',
    '¬¬¬ Utpressing',
    '¬¬¬ Annet eller uspesifisert ran og utpressing',
    '¬¬ Tvang',
    '¬¬ Frihetsberøvelse',
    '¬¬ Omsorgs- og familieforhold',
    '¬¬ Hensynsløs atferd og personforfølgelse',
    '¬¬ Menneskehandel',
    '¬¬ Terror og terrorrelatert handling',
    '¬¬ Annen vold og mishandling',
    '¬ Seksuallovbrudd',
    '¬¬ Voldtekt, i alt',
    '¬¬¬ Voldtekt',
    '¬¬¬¬ Voldtekt, barn under 14 år',
    '¬¬¬¬ Voldtekt, annen eller uspesifisert alder',
    '¬¬¬ Grov voldtekt',
    '¬¬¬¬ Grov voldtekt, barn under 14 år (fra 1.10.2015)',
    '¬¬¬¬ Grov voldtekt, annen eller uspesifisert alder',
    '¬¬ Voldtekt, forsøk',
    '¬¬ Seksuell omgang i overmaktsforhold',
    '¬¬ Seksuell omgang, barn 14-15 år',
    '¬¬ Seksuell omgang mellom nærstående',
    '¬¬ Seksuell handling',
    '¬¬¬ Seksuell handling, barn under 16 år',
    '¬¬¬ Annen seksuell handling uten samtykke',
    '¬¬ Seksuelt krenkende atferd',
    '¬¬¬ Seksuelt krenkende atferd, barn under 16 år (fra 1.10.2015)',
    '¬¬¬ Seksuelt krenkende atferd, annen eller uspesifisert alder',
    '¬¬ Annet eller uspesifisert seksuallovbrudd',
    '¬ Rusmiddellovbrudd',
    '¬¬ Narkotikalovbrudd',
    '¬¬¬ Narkotika, legemiddelloven',
    '¬¬¬¬ Narkotika, bruk',
    '¬¬¬¬ Narkotika, mindre besittelse',
    '¬¬¬ Narkotika, straffeloven, i alt',
    '¬¬¬¬ Narkotikaovertredelse, straffeloven',
    '¬¬¬¬ Grov narkotikaovertredelse, straffeloven',
    '¬¬ Doping',
    '¬¬¬ Doping, legemiddelloven',
    '¬¬¬ Doping, straffeloven',
    '¬¬ Ruspåvirket kjøring',
    '¬¬¬ Promillekjøring, veitrafikk',
    '¬¬¬ Promillekjøring, annet',
    '¬¬ Alkohollovovertredelse, i alt',
    '¬¬¬ Alkohollovovertredelse',
    '¬¬¬ Grov alkohollovovertredelse',
    '¬¬ Annet eller uspesifisert rusmiddellovbrudd',
    '¬ Ordens- og integritetskrenkelse',
    '¬¬ Offentlig ordenskrenkelse',
    '¬¬¬ Ordensforstyrrelse, i alt',
    '¬¬¬¬ Regional ordensvedtekt, urinering og annet',
    '¬¬¬¬ Ordensforstyrrelse i selvforskyldt rus',
    '¬¬¬¬ Annen eller uspesifisert ordensforstyrrelse',
    '¬¬¬ Våpen-, brann- og eksplosivlovgivning',
    '¬¬¬¬ Bevæpning på offentlig sted',
    '¬¬¬¬ Annet eller uspesifisert våpenlovbrudd',
    '¬¬¬¬ Brann- og eksplosivlovgivning',
    '¬¬ Myndighetskrenkelse',
    '¬¬¬ Hindre og motarbeide offentlig myndighet',
    '¬¬¬¬ Hindre og forulempe offentlig tjenesteperson',
    '¬¬¬¬¬ Forulempe offentlig tjenesteperson',
    '¬¬¬¬¬ Hindre offentlig tjenesteperson',
    '¬¬¬¬ Motarbeide retts- og straffeforfølgning',
    '¬¬¬¬¬ Identifikasjonsplikt overfor offentlig myndighet',
    '¬¬¬¬¬ Oppholds- og kontaktforbud',
    '¬¬¬¬¬ Annet pålegg fra politi og annen myndighet',
    '¬¬¬¬¬ Motarbeide straffegjennomføring',
    '¬¬¬¬¬ Annet, motarbeide retts- og straffeforfølgning',
    '¬¬¬ Uriktig forklaring og anklage',
    '¬¬¬¬ Uriktig forklaring',
    '¬¬¬¬ Uriktig anklage',
    '¬¬¬ Utlendingslovgivning',
    '¬¬¬¬ Innreiseforbud',
    '¬¬¬¬ Bistå ulovlig innreise og opphold',
    '¬¬¬¬ Annen eller uspesifisert utlendingslovgivning',
    '¬¬¬ Tjenestefeil og misbruk av offentlig myndighet',
    '¬¬¬ Annen eller uspesifisert myndighetskrenkelse',
    '¬¬ Integritetskrenkelse',
    '¬¬¬ Dokument- og ID-krenkelse',
    '¬¬¬¬ Dokumentfalsk',
    '¬¬¬¬¬ Dokumentfalsk, bruk',
    '¬¬¬¬¬ Dokumentfalsk, tilvirket og anskaffet',
    '¬¬¬¬ Pengefalsk',
    '¬¬¬¬ ID-krenkelse (fra 1.10.2015)',
    '¬¬¬¬¬ ID-krenkelse, befatning (fra 1.10.2015)',
    '¬¬¬¬¬ ID-krenkelse, bruk (fra 1.10.2015)',
    '¬¬¬¬ Annen eller uspesifisert dokument- og ID-krenkelse',
    '¬¬¬ Uberettiget adgang og opphold',
    '¬¬¬¬ Inntrengning i bygning og annet sted',
    '¬¬¬¬ Inntrengning i data- og kommunikasjonssystem',
    '¬¬¬ Offentlig krenkelse av privatlivets fred',
    '¬¬¬ Hatefulle ytringer og diskriminering',
    '¬¬¬ Annen eller uspesifisert integritetskrenkelse',
    '¬ Trafikkovertredelse',
    '¬¬ Veitrafikkovertredelse',
    '¬¬¬ Uten gyldig førerkort',
    '¬¬¬ Ulovlig hastighet',
    '¬¬¬ Personskade',
    '¬¬¬ Annen eller uspesifisert veitrafikkovertredelse',
    '¬¬ Annen transport- og trafikklovgivning',
    '¬ Annet lovbrudd',
    '¬¬ Natur- og miljølovbrudd',
    '¬¬¬ Allmennfarlig forgiftning og alvorlig miljølovbrudd',
    '¬¬¬ Jakt-, fangst- og fiskerilovbrudd',
    '¬¬¬ Annet natur- og miljølovbrudd',
    '¬¬ Arbeidsmiljølovgivning',
    '¬¬ Annen eller uspesifisert straffelovgivning',
    'I alt',
    'Forbrytelser',
    'Forseelser',
    'Alle lovbruddsgrupper',
    'Økonomisk kriminalitet',
    'Annen vinningskriminalitet',
    'Voldskriminalitet',
    'Seksualkriminalitet',
    'Narkotikakriminalitet',
    'Skadeverk',
    'Miljøkriminalitet',
    'Arbeidsmiljøkriminalitet',
    'Trafikkriminalitet',
    'Annen kriminalitet',
    'Alle typer lovbrudd',
    '¬ Forbrytelser',
    '¬¬ Forbrytelse mot straffeloven',
    '¬¬¬ Forbrytelse mot statens selvstendighet og sikkerhet',
    '¬¬¬ Forbrytelse mot Norges statsforfatning og statsoverhode',
    '¬¬¬¬ Forbrytelse mot statsmaktene',
    '¬¬¬¬ Annet, forbrytelse mot Norges statsforfatning og statsoverhode',
    '¬¬¬ Forbrytelse mht. utøvelse av statsborgerlige rettigheter',
    '¬¬¬ Forbrytelse i den offentlige tjeneste',
    '¬¬¬¬ Vinningsforbrytelse i den offentlig tjeneste',
    '¬¬¬¬ Brevbrudd (offentlig tjeneste)',
    '¬¬¬¬ Misbruk av myndighet',
    '¬¬¬¬ Annet, forbrytelse i den offentlige tjeneste',
    '¬¬¬ Forbrytelse mot den offentlige myndighet',
    '¬¬¬¬ Vold mot offentlig tjenestemann',
    '¬¬¬¬ Ulovlig påvirkning av offentlig tjenestemann',
    '¬¬¬¬ Motarbeiding av etterforskning, medvirkning til rømming',
    '¬¬¬¬ Annet, forbrytelse mot den offentlige myndighet',
    '¬¬¬ Forbrytelse mot den alminnelige orden og fred',
    '¬¬¬¬ Opprør og oppløp mv.',
    '¬¬¬¬ Rasediskriminering',
    '¬¬¬¬ Oppfordring til straffbar handling mv.',
    '¬¬¬¬ Brevbrudd (orden og fred)',
    '¬¬¬¬ Innbrudd',
    '¬¬¬¬ Annet, forbrytelse mot den alminnelige orden og fred',
    '¬¬¬ Allmennfarlig forbrytelse',
    '¬¬¬¬ Forsettlig forvoldelse av ildebrann',
    '¬¬¬¬ Uaktsom forvoldelse av ildebrann',
    '¬¬¬¬ Narkotikaforbrytelse (straffeloven)',
    '¬¬¬¬ Grov narkotikaforbrytelse (straffeloven)',
    '¬¬¬¬ Annet, allmennfarlig forbrytelse',
    '¬¬¬ Falsk forklaring',
    '¬¬¬ Falsk anklage',
    '¬¬¬¬ Forsettlig falsk anklage',
    '¬¬¬¬ Annet, falsk anklage',
    '¬¬¬ Pengefalsk',
    '¬¬¬ Dokumentfalsk',
    '¬¬¬¬ Benyttelse av falskt dokument',
    '¬¬¬¬ Forfalskning av dokument',
    '¬¬¬¬ Annet, dokumentfalsk',
    '¬¬¬ Seksualforbrytelser',
    '¬¬¬¬ Voldtekt',
    '¬¬¬¬ Seksuell omgang m/trusler, underfundig adferd o.l.',
    '¬¬¬¬ Seksuell omgang med bevisstløs',
    '¬¬¬¬ Voldtektsforsøk',
    '¬¬¬¬ Incest',
    '¬¬¬¬ Seksuell omgang med barn',
    '¬¬¬¬¬ Seksuell omgang med barn under 10 år',
    '¬¬¬¬¬ Seksuell omgang med barn under 14 år',
    '¬¬¬¬¬ Seksuell omgang med barn under 16 år',
    '¬¬¬¬ Annen seksuell omgang',
    '¬¬¬¬ Seksuell handling med barn under 16 år',
    '¬¬¬¬ Seksuelt krenkende eller annen uanstendig atferd',
    '¬¬¬¬ Pornografi',
    '¬¬¬¬ Annet, seksualforbrytelser',
    '¬¬¬ Forbrytelse mht. familieforhold',
    '¬¬¬¬ Misligholdt forsørgelsesplikt mv.',
    '¬¬¬¬ Inngåelse av ugyldig eller omstøtelig ekteskap',
    '¬¬¬¬ Bortføring av barn',
    '¬¬¬¬ Mishandling i familieforhold',
    '¬¬¬¬ Grov mishandling i familieforhold',
    '¬¬¬¬ Annet, forbrytelse mht. familieforhold',
    '¬¬¬ Forbrytelse mot den personlige frihet',
    '¬¬¬¬ Trusler',
    '¬¬¬¬ Tvang/frihetsberøvelse',
    '¬¬¬¬ Annet, forbrytelse mot den personlige frihet',
    '¬¬¬ Forbrytelse mot liv, legeme og helbred',
    '¬¬¬¬ Legemsfornærmelse',
    '¬¬¬¬ Legemsbeskadigelse',
    '¬¬¬¬ Grov legemsbeskadigelse',
    '¬¬¬¬ Uaktsom legemsbeskadigelse',
    '¬¬¬¬ Drapsforsøk',
    '¬¬¬¬ Drap',
    '¬¬¬¬ Uaktsomt drap',
    '¬¬¬¬ Annet, forbrytelse mot liv, legeme og helbred',
    '¬¬¬ Ærekrenkelse',
    '¬¬¬ Underslag',
    '¬¬¬¬ Simpelt underslag',
    '¬¬¬¬ Grovt underslag',
    '¬¬¬ Tyveri',
    '¬¬¬¬ Simpelt tyveri',
    '¬¬¬¬¬ Simpelt tyveri fra bedrift, kontor og lager',
    '¬¬¬¬¬ Simpelt tyveri fra butikk',
    '¬¬¬¬¬ Simpelt tyveri fra leilighet, bolighus og hytte',
    '¬¬¬¬¬ Simpelt tyveri fra oppgang, loft, kjeller, garasje og uthus',
    '¬¬¬¬¬ Simpelt tyveri fra offentlig bygning og institusjon',
    '¬¬¬¬¬ Simpelt tyveri fra befordringsmiddel',
    '¬¬¬¬¬ Simpelt tyveri fra kafé og restaurant',
    '¬¬¬¬¬ Simpelt tyveri fra garderobe',
    '¬¬¬¬¬ Simpelt tyveri, sykkeltyveri',
    '¬¬¬¬¬ Annet simpelt tyveri',

In [91]:
import json

ssb_query_str = """
{
  "query": [
    {
      "code": "LovbruddKrim",
      "selection": {
        "filter": "item",
        "values": [
          "1AAAAA-9ZZZZz",
          "1AAAAA-1ZZZZz",
          "2AAAAA-2ZZZZz",
          "BIZZZ",
          "BZZZZ"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "AnmeldteLovbrudd",
          "AnmLovbrPer1000"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "1993",
          "1994",
          "1995",
          "2022",
          "2023"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}
"""
ssb_query = json.loads(ssb_query_str)
ssb_query["query"][0]["selection"]["values"] = list(set(items))
ssb_query

{'query': [{'code': 'LovbruddKrim',
   'selection': {'filter': 'item',
    'values': ['1ACDZZ',
     '1ACCAA-1ACCZZ',
     'AARAE',
     'AARAZ',
     'AARAG',
     'AARAI',
     '1ACZZZ',
     '1ACEBZ',
     '1ACECZ',
     '1ABEAZ',
     '1ABFZZ',
     '1AAAAA-1AZZZZ',
     '1AAZZZ',
     'AARAC',
     'AARAH',
     'AARBC',
     'AARCA',
     'AARAA-AARAZ',
     '1ABHCZ',
     '1AAAAA-1AAZZZ',
     'AARAF',
     'AARBB',
     '1ABHBZ',
     'AARBE',
     'AARAA-AARZZ',
     '1ADAZZ',
     'AARAA',
     'AARAD',
     '1ACAAA-1ACZZZ',
     '1ABHZZ',
     '1ABEAA-1ABEZZ',
     'AARBD',
     'AARBZ',
     '1AAAZZ',
     '1ADBZZ',
     '1ABAAA-1ABZZZ',
     'AARCB',
     '1ABHAA-1ABHZZ',
     '1ABDZZ',
     '1ABHAZ',
     '1ACBZZ',
     '1ACEAA-1ACEZZ',
     '1ABEBZ',
     'AARBA',
     'AARAB',
     '1ACCAZ',
     '1ACEZZ',
     'AARBA-AARBZ',
     '1ABHDZ',
     '1ACCBZ',
     '1ACCCZ',
     '1ABCZZ',
     'AARCZ',
     '1AAAAA-1ZZZZz',
     'AARCA-AARCZ',
     '1ABECZ',
     '1ACAZZ',
     '1ADZZZ',
     '1AAAAA-1ZZZZZ',
     '1ABZZZ',
     '1ACEDZ',
     '1ADAAA-1ADZZZ',
     '1ACEAZ',
     '1ABGZZ']}},
  {'code': 'ContentsCode',
   'selection': {'filter': 'item',
    'values': ['AnmeldteLovbrudd', 'AnmLovbrPer1000']}},
  {'code': 'Tid',
   'selection': {'filter': 'item',
    'values': ['1993', '1994', '1995', '2022', '2023']}}],
 'response': {'format': 'json-stat2'}}

In [92]:
respons_query = requests.post(url, json=ssb_query)
respons_query.status_code

200

In [93]:
ds = pyjstat.Dataset.read(respons_query.text)
df = ds.write('dataframe')
df_id = ds.write('dataframe', naming='id')
df =df.set_index(["statistikkvariabel", "lovbruddstype", "år"])
df[~df.duplicated()]
df

                                                                                                 value
statistikkvariabel                   lovbruddstype                                      år
Lovbrudd anmeldt                     ¬ Eiendomstyveri                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   99729.0
                                                                                        2023  111584.0
Lovbrudd anmeldt per 1000 innbyggere ¬ Eiendomstyveri                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022      18.4
                                                                                        2023      20.3
Lovbrudd anmeldt                     ¬ Eiendomstyveri                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   99729.0
                                                                                        2023  111584.0
Lovbrudd anmeldt per 1000 innbyggere ¬ Eiendomstyveri                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬ Tyveri, i alt                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   99312.0
                                                                                        2023  110995.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬ Tyveri, i alt                                   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬ Mindre tyveri                                  1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   13391.0
                                                                                        2023   16809.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬ Mindre tyveri                                  1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Mindre tyveri fra butikk og annet salgssted   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   12052.0
                                                                                        2023   15467.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Mindre tyveri fra butikk og annet salgssted   1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Annet eller uspesifisert mindre tyveri        1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    1339.0
                                                                                        2023    1342.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Annet eller uspesifisert mindre tyveri        1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬ Tyveri                                         1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   77804.0
                                                                                        2023   84264.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬ Tyveri                                         1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri fra butikk og annet salgssted          1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    6381.0
                                                                                        2023    7410.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri fra butikk og annet salgssted          1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri fra annen næring og offentlig virks... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    5604.0
                                                                                        2023    7334.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri fra annen næring og offentlig virks... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri fra bolig og fritidsbolig              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   11739.0
                                                                                        2023   13818.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri fra bolig og fritidsbolig              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra bolig                             1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    2727.0
                                                                                        2023    3004.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra bolig                             1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra fritidsbolig                      1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022     314.0
                                                                                        2023     308.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra fritidsbolig                      1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra bod, garasje og areal til boli... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    8698.0
                                                                                        2023   10506.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra bod, garasje og areal til boli... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri fra bil og annet motorkjøretøy         1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    8094.0
                                                                                        2023    8740.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri fra bil og annet motorkjøretøy         1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri av sykkel                              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   19789.0
                                                                                        2023   18854.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri av sykkel                              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬ Tyveri fra person                             1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022   26188.0
                                                                                        2023   28099.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬ Tyveri fra person                             1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra person i salgslokale              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    7402.0
                                                                                        2023    7603.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra person i salgslokale              1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra person i kollektiv transport (... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    4953.0
                                                                                        2023    5427.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra person i kollektiv transport (... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra person i gate, park, annet fri... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022    3655.0
                                                                                        2023    3772.0
Lovbrudd anmeldt per 1000 innbyggere ¬¬¬¬¬ Tyveri fra person i gate, park, annet fri... 1993       NaN
                                                                                        1994       NaN
                                                                                        1995       NaN
                                                                                        2022       NaN
                                                                                        2023       NaN
Lovbrudd anmeldt                     ¬¬¬¬¬ Tyveri fra person i anlegg for idrett, ku... 1993       NaN
                                                                                        1994       NaN