In [66]:
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import numpy as np


df = pd.read_csv("handelkjottfrukt.csv", encoding="ISO-8859-1", sep="\t")
display(df)
df = df.melt(id_vars=["næring (SN2007)", "statistikkvariabel"], var_name="År", value_name="omsetning1")
display(df)
df = df.pivot(index="År", columns=["næring (SN2007)"], values="omsetning1")
df

  statistikkvariabel                              næring (SN2007)  ...   2023   2024
0          Omsetning  46.310 Engroshandel med frukt og grønnsaker  ...  32636  20885
1          Omsetning  46.320 Engroshandel med kjøtt og kjøttvarer  ...   2312   1294

[2 rows x 19 columns]

                                næring (SN2007)  ... omsetning1
0   46.310 Engroshandel med frukt og grønnsaker  ...          0
1   46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
2   46.310 Engroshandel med frukt og grønnsaker  ...          0
3   46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
4   46.310 Engroshandel med frukt og grønnsaker  ...          0
5   46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
6   46.310 Engroshandel med frukt og grønnsaker  ...          0
7   46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
8   46.310 Engroshandel med frukt og grønnsaker  ...          0
9   46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
10  46.310 Engroshandel med frukt og grønnsaker  ...          0
11  46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
12  46.310 Engroshandel med frukt og grønnsaker  ...      16334
13  46.320 Engroshandel med kjøtt og kjøttvarer  ...       3209
14  46.310 Engroshandel med frukt og grønnsaker  ...      18664
15  46.320 Engroshandel med kjøtt og kjøttvarer  ...       1925
16  46.310 Engroshandel med frukt og grønnsaker  ...      18832
17  46.320 Engroshandel med kjøtt og kjøttvarer  ...       2072
18  46.310 Engroshandel med frukt og grønnsaker  ...      19178
19  46.320 Engroshandel med kjøtt og kjøttvarer  ...       1963
20  46.310 Engroshandel med frukt og grønnsaker  ...      19709
21  46.320 Engroshandel med kjøtt og kjøttvarer  ...       1965
22  46.310 Engroshandel med frukt og grønnsaker  ...      20027
23  46.320 Engroshandel med kjøtt og kjøttvarer  ...       2004
24  46.310 Engroshandel med frukt og grønnsaker  ...      20854
25  46.320 Engroshandel med kjøtt og kjøttvarer  ...       2542
26  46.310 Engroshandel med frukt og grønnsaker  ...          0
27  46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
28  46.310 Engroshandel med frukt og grønnsaker  ...          0
29  46.320 Engroshandel med kjøtt og kjøttvarer  ...          0
30  46.310 Engroshandel med frukt og grønnsaker  ...      32636
31  46.320 Engroshandel med kjøtt og kjøttvarer  ...       2312
32  46.310 Engroshandel med frukt og grønnsaker  ...      20885
33  46.320 Engroshandel med kjøtt og kjøttvarer  ...       1294

[34 rows x 4 columns]

næring (SN2007)  46.310 Engroshandel med frukt og grønnsaker  46.320 Engroshandel med kjøtt og kjøttvarer
År
2008                                                       0                                            0
2009                                                       0                                            0
2010                                                       0                                            0
2011                                                       0                                            0
2012                                                       0                                            0
2013                                                       0                                            0
2014                                                   16334                                         3209
2015                                                   18664                                         1925
2016                                                   18832                                         2072
2017                                                   19178                                         1963
2018                                                   19709                                         1965
2019                                                   20027                                         2004
2020                                                   20854                                         2542
2021                                                       0                                            0
2022                                                       0                                            0
2023                                                   32636                                         2312
2024                                                   20885                                         1294

In [59]:
data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03'],
    'Store': ['Store A', 'Store B', 'Store A', 'Store B', 'Store A', 'Store B'],
    'Product': ['Apples', 'Apples', 'Oranges', 'Oranges', 'Apples', 'Apples'],
    'Sales': [100, 150, 120, 130, 110, 140],
    'Revenue': [200, 300, 240, 260, 220, 280]
}

df = pd.DataFrame(data)
df.pivot(index=["Date", "Store"], columns="Product", values=["Sales", "Revenue"])

                    Sales         Revenue
Product            Apples Oranges  Apples Oranges
Date       Store
2023-01-01 Store A  100.0     NaN   200.0     NaN
           Store B  150.0     NaN   300.0     NaN
2023-01-02 Store A    NaN   120.0     NaN   240.0
           Store B    NaN   130.0     NaN   260.0
2023-01-03 Store A  110.0     NaN   220.0     NaN
           Store B  140.0     NaN   280.0     NaN