## Oppgave 6.1

* Lag dataframen vist under
<img src="https://folk.ntnu.no/jonajh/iira2001/42/img/oppgave1.png">

* Programmet er påbegynt under
* Merk at det trekkes tilfeldige tall, slik at tallverdiene ikke blir nøyaktig de samme som på figuren

*Tips:* For å formatere heltall til 2 plasser med innledende nuller i en f-streng: 
`f"heltallet mitt er {tall:02d}"`

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

n = 180
populasjon = np.random.normal(10.0,0.1,n) # Trekker tilfeldige tall med normalfordeling rundt 10
arbeidsledighet = np.random.normal(0.03,0.002,n) # Trekker tilfeldig arbeidsledighet, normalfordelt

indeks = [f"{year}M{month:02d}"
              for year in range(1990, 2005)
              for month in range(1,13)
         ]
arbeidsledighet_formatert = [f"{ledighet:.2%}" for ledighet in arbeidsledighet]
df = pd.DataFrame({"Populasjon (million)": populasjon, "Arbeidsledighet": arbeidsledighet_formatert}, index=indeks)

df["arbeidsledighet_decimal"] = arbeidsledighet
df["Antall uten arbeid(tusen)"] = df["arbeidsledighet_decimal"]*df["Populasjon (million)"]*1000
df["Antall uten arbeid(tusen)"] = df["Antall uten arbeid(tusen)"].apply(lambda tall: int(round(tall,0)))
df = df.drop(columns="arbeidsledighet_decimal")
display(df)

#Alternativ med pandas.Period som indeks
indeksPeriode = pd.period_range('1990', '2005', freq='M') #Lag periodeindeks
df2 = df.set_index(indeksPeriode[:-1]) # Sett ny indeks -- indeksPeriode går til og med 2005-01, derfor slicer vi
df2

         Populasjon (million) Arbeidsledighet  Antall uten arbeid(tusen)
1990M01              9.998851           3.02%                        302
1990M02              9.963289           2.85%                        284
1990M03              9.897512           2.97%                        294
1990M04              9.934626           2.98%                        296
1990M05              9.847170           2.55%                        251
...                       ...             ...                        ...
2004M08             10.021540           2.86%                        286
2004M09             10.006361           2.90%                        290
2004M10             10.100813           2.89%                        292
2004M11              9.981591           2.50%                        250
2004M12              9.830516           3.16%                        311

[180 rows x 3 columns]

         Populasjon (million) Arbeidsledighet  Antall uten arbeid(tusen)
1990-01              9.998851           3.02%                        302
1990-02              9.963289           2.85%                        284
1990-03              9.897512           2.97%                        294
1990-04              9.934626           2.98%                        296
1990-05              9.847170           2.55%                        251
...                       ...             ...                        ...
2004-08             10.021540           2.86%                        286
2004-09             10.006361           2.90%                        290
2004-10             10.100813           2.89%                        292
2004-11              9.981591           2.50%                        250
2004-12              9.830516           3.16%                        311

[180 rows x 3 columns]

# Oppgave 6.2
Når du har gjort 6.1 sjekk at du kan slå opp i dataframe ved å:
1. Hente ut enkteltvise kolonner
2. Hente ut flere kolonner
3. Hente ut en rad
4. Hente ut flere rader
5. Hente ut enkeltvise datapunkt
6. Hente ut rader ved å slice (feks fra november 2003 til august 2004)
7. Hente ut deler av dataframe med å slice radene og velge 1 eller flere av kolonnene

In [22]:
#1 Enkeltkolonner
print("1:")
display(df2["Arbeidsledighet"])

#2 Flere kolonner
print("2:")
display(df2[["Arbeidsledighet", "Populasjon (million)"]])

#Enkeltrad
print("3:")
display(df2.iloc[2]) #tredje rad

1:

1990-01    2.91%
1990-02    3.29%
1990-03    2.82%
1990-04    3.31%
1990-05    3.02%
           ...
2004-08    3.32%
2004-09    2.75%
2004-10    2.92%
2004-11    2.90%
2004-12    3.03%
Freq: M, Name: Arbeidsledighet, Length: 180, dtype: object

2:

        Arbeidsledighet  Populasjon (million)
1990-01           2.91%             10.026103
1990-02           3.29%              9.864531
1990-03           2.82%             10.077345
1990-04           3.31%             10.066700
1990-05           3.02%              9.902772
...                 ...                   ...
2004-08           3.32%              9.982786
2004-09           2.75%              9.889700
2004-10           2.92%              9.979237
2004-11           2.90%             10.013628
2004-12           3.03%             10.137002

[180 rows x 2 columns]

3:

Populasjon (million)         10.077345
Arbeidsledighet                  2.82%
Antall uten arbeid(tusen)          284
Name: 1990-03, dtype: object

In [27]:
#4 Flere rader
print("4:")
display(df2.loc[["1990-06", "2003-10"]])

#Enkeltvise datapunkter
print("5:")
print("Populasjon 2002-04: ", df2.loc["2002-04", "Populasjon (million)"])

#

4:

         Populasjon (million) Arbeidsledighet  Antall uten arbeid(tusen)
1990-06              9.927935           3.39%                        336
2003-10              9.875529           3.05%                        301

5:
Populasjon 2002-04:  9.886250348435892

In [30]:
#6 slice rader
print("6:")
display(df2.loc["1995-03":"2000Q3"]) #Vi kan slice med dato/måned og kvartal samtidig med periodindex

#7 Slice og velge
print("7:")
display(df2.loc["1995-03":"2000Q3", ["Populasjon (million)", "Antall uten arbeid(tusen)"]])

6:

         Populasjon (million) Arbeidsledighet  Antall uten arbeid(tusen)
1995-03             10.069598           2.78%                        280
1995-04             10.123900           2.66%                        269
1995-05              9.963029           3.05%                        304
1995-06              9.812459           2.93%                        288
1995-07             10.038575           2.73%                        274
...                       ...             ...                        ...
2000-05             10.042867           3.11%                        312
2000-06             10.096087           3.42%                        345
2000-07             10.067881           2.79%                        281
2000-08             10.060186           2.73%                        275
2000-09              9.943098           3.18%                        316

[67 rows x 3 columns]

7:

         Populasjon (million)  Antall uten arbeid(tusen)
1995-03             10.069598                        280
1995-04             10.123900                        269
1995-05              9.963029                        304
1995-06              9.812459                        288
1995-07             10.038575                        274
...                       ...                        ...
2000-05             10.042867                        312
2000-06             10.096087                        345
2000-07             10.067881                        281
2000-08             10.060186                        275
2000-09              9.943098                        316

[67 rows x 2 columns]

# Oppgave 6.3

Vi skal lage en funksjon som hjelper oss med å omgjøre dataframes med data for hver måned til hvert kvartal
og hvert kvartal til hvert år.

* Anta at tidene er på formene:
    - yyyyKq feks 1983K2 for  andre kvartal 1983
    - yyyyMmm feks 2001M03 for mars (måned 3) i 2001
    - yyyy feks 2020
* Lag to funksjoner:
    - Det ene tar et dataframe med index på månedsformen og gir tilbake et på kvartalsformen
    - Den andre funksjonen tar et dataframe med index på kvartalsformen og gir tilbake et på «årsformen»

Anta først at dataframen kun har 1 kolonne. Når du har fått det til kan du gjøre om funksjonen slik at den
fungerer med flere kolonner.

Et par ting å ta hensyn til/problemer å løse:

* Noen ganger gir det mening å legge sammen dataene fra månedene i et kvartal, feks ved åpnede konkurser
* Andre ganger må man gjøre noe annet, feks ved arbeidsledighet kanskje man tar gjennomsnittet
* Hvordan lage en funksjon som tar hensyn til dette ved kun 1 kolonne og ved flere kolonner?
* Hva med kolonner som gir prosent som en streng `"2.1%"`i stedet for `0.021`, kan vi tilpasse funksjonen?

Du kan teste funksjonene dine på dataframe vi lagde i 6.1, eller i settene i 6.4
Forslag på funksjon er påbegynt i cellene under

In [68]:
import datetime


def month_to_quarter(df, kumulative=[]):
    """
    df: dataframe med indeks på månedsform yyyyMmm (ie 1987M04 = april 1987)
    
    kumulative: En liste med kolonnenavn hvor kvartalsverdien 
        skal være summen av månedsverdiene. Default er en tom liste.
        For øvrige kolonner blir kvartalsverdien gjennomsnittsverdien av månedsverdiene

    Funksjonen returnerer et nytt dataframe med indeks på kvartalsform yyyyKq (ie 1987K2 for andre kvartal 1987)
    """
    # Kode Kode
    dato = df.index.map(lambda x: datetime.datetime.strptime(str(x), "%YM%m"))
    kvartal = dato.to_period('Q')
    kvartal.name = "kvartal"
    df2 = df.set_index(kvartal)
    group = df2.groupby("kvartal")
    df_new = pd.DataFrame(index=df2.index)
    for col in df.columns:
        if col in kumulative and df[col].dtype not in ['object', 'string']:
            df_new[col] = group[col].sum()
        elif df[col].dtype not in ['object', 'string']:
            df_new[col] = group[col].mean()
    
    return df_new.drop_duplicates()

In [67]:
def quarter_to_year(df, kumulative=[]):
    """
    df: dataframe med indeks på kvartalsform yyyyKk (ie 1987K2 = andre kvartal 1987)
    
    kumulative: En liste med kolonnenavn hvor årsverdien 
        skal være summen av kvartalsverdiene. Default er en tom liste.
        For øvrige kolonner blir årsverdien gjennomsnittsverdien av kvartalsverdiene

    Funksjonen returnerer et nytt dataframe med indeks på årsform yyyy (ie 1987 for herrens år 1987)
    """
    # Kode Kode
    dato = df.index.map(lambda x: datetime.datetime.strptime(str(x), "%YQ%S")) #Les til datetime
    year = dato.to_period('Y') #Gjør om til pandas periode
    year.name = "year" #sett navn
    df2 = df.set_index(year) #lag ny dataframe med nye year indeks
    group = df2.groupby("year") #Grupper alle år kvartal i året
    df_new = pd.DataFrame(index=df2.index) 
    for col in df.columns:
        if col in kumulative and df[col].dtype not in ['object', 'string']:
            df_new[col] = group[col].sum()
        elif df[col].dtype not in ['object', 'string']:
            df_new[col] = group[col].mean()
    
    return df_new.drop_duplicates()

In [36]:
arbeidsledige_df = pd.read_csv("08518_20231018-095706.csv", sep="\t")
konkurser_df = pd.read_csv("09695_20231018-104409.csv", sep="\t", encoding="ISO-8859-1")
konkurser_df.set_index("måned", inplace=True)

In [69]:
df_sjekk = month_to_quarter(df)

In [71]:
df_sjekk2 = quarter_to_year(df_sjekk)

In [72]:
df_sjekk2

      Populasjon (million)  Antall uten arbeid(tusen)
year
1990              9.944435                 293.750000
1991              9.983000                 295.166667
1992              9.996177                 301.333333
1993             10.023079                 301.250000
1994             10.018008                 309.500000
1995             10.000514                 299.416667
1996              9.982488                 286.833333
1997             10.028061                 300.083333
1998              9.994127                 300.333333
1999             10.032830                 297.500000
2000             10.005239                 295.750000
2001             10.043393                 299.666667
2002             10.023189                 299.583333
2003             10.019406                 303.083333
2004              9.982230                 297.083333