# Demo kjeldehenvising

Fylgjande kode lånte eg frå StackExchange[^1].

[^1]: [Post av John Doe](https://www.stackexchange.com/)

In [1]:
class Klassami:
   def __init__(self,namn):
       self.namn = namn
   def __str__(self):
       return self.namn
objektetmitt = Klassami("Et namn skal barnet ha")

In [2]:
print( objektetmitt )

Et namn skal barnet ha

## Marknadsverdi

In [3]:
import pandas as pd

In [4]:
a = pd.Series( { "x" : 5, "y" : 10 }, name="Aksje" )
b = pd.Series( { "x" : 4, "y" : 3 }, name="Statsobligasjon" )
print( a )
print(  b )

x     5
y    10
Name: Aksje, dtype: int64
x    4
y    3
Name: Statsobligasjon, dtype: int64

In [5]:
df = pd.DataFrame( [ a, b ] )
display( df )

                 x   y
Aksje            5  10
Statsobligasjon  4   3

In [6]:
import helpers as h

In [8]:
h.marknadsverdi( df.loc["Aksje"] )

np.int64(50)

In [9]:
print( f"{h.marknadsverdi( df.loc["Aksje"] )}" )

50

In [10]:
df['marknadsverdi'] = df.apply( h.marknadsverdi, axis=1)

In [11]:
display( df )

                 x   y  marknadsverdi
Aksje            5  10             50
Statsobligasjon  4   3             12

In [ ]:
from helpers import *