In [16]:
import pandas as pd

df = pd.read_csv("studenter-bb.xls", encoding="UTF-16",sep='\t')
df_moodle = df.rename(columns={
    'Etternavn': 'lastname',
    'Fornavn': 'firstname',
    'Brukernavn': 'username',
    'Student-ID': 'idnumber'
})
df_moodle=df_moodle.drop(columns=["Unnamed: 4"])
df_moodle.insert(4, 'email', [f"{u}@stud.ntnu.no" for u in df_moodle["username"].values])
df_moodle

     lastname           firstname  username  idnumber                  email
0     Aarseth     Bernhard August   bernhaa    725285   bernhaa@stud.ntnu.no
1        Aase       Didrik Handal  didrikaa    590882  didrikaa@stud.ntnu.no
2      Alieva              Fatima  fatimaal    590864  fatimaal@stud.ntnu.no
3     Aschjem       Vemund Støren  vemundsa    590453  vemundsa@stud.ntnu.no
4    Assersen     Celine Leidland   celinla    590452   celinla@stud.ntnu.no
..        ...                 ...       ...       ...                    ...
142  Vågsæter  Rebecca Andreassen   rebeccv    590439   rebeccv@stud.ntnu.no
143      With         Simon Andrè  simonawi    524082  simonawi@stud.ntnu.no
144  Ørneberg           Sebastian  sebastor    590900  sebastor@stud.ntnu.no
145    Øverås              Daniel    daniov    568403    daniov@stud.ntnu.no
146    Øverås              Emilie   emiliov    109360   emiliov@stud.ntnu.no

[147 rows x 5 columns]

In [18]:
from numpy import who
import pandas as pd 
df = pd.read_csv("studenter-bb.xls", encoding="UTF-16", header=0, sep='\t')
df_moodle = df.rename(columns={
    'Etternavn': 'lastname',
    'Fornavn': 'firstname',
    'Brukernavn': 'username',
    'Student-ID': 'idnumber'
})
df_moodle = df_moodle.drop(columns=["Unnamed: 4"])
df_moodle.insert(4, 'email', [f"{u}@stud.ntnu.no" for u in df_moodle["username"].values])
df_moodle

     lastname           firstname  username  idnumber                  email
0     Aarseth     Bernhard August   bernhaa    725285   bernhaa@stud.ntnu.no
1        Aase       Didrik Handal  didrikaa    590882  didrikaa@stud.ntnu.no
2      Alieva              Fatima  fatimaal    590864  fatimaal@stud.ntnu.no
3     Aschjem       Vemund Støren  vemundsa    590453  vemundsa@stud.ntnu.no
4    Assersen     Celine Leidland   celinla    590452   celinla@stud.ntnu.no
..        ...                 ...       ...       ...                    ...
142  Vågsæter  Rebecca Andreassen   rebeccv    590439   rebeccv@stud.ntnu.no
143      With         Simon Andrè  simonawi    524082  simonawi@stud.ntnu.no
144  Ørneberg           Sebastian  sebastor    590900  sebastor@stud.ntnu.no
145    Øverås              Daniel    daniov    568403    daniov@stud.ntnu.no
146    Øverås              Emilie   emiliov    109360   emiliov@stud.ntnu.no

[147 rows x 5 columns]