# Avfall
* SSB tabell 14458: Industriavfall. Generert mengde avfall (1 000 tonn), etter materialtype, statistikkvariabel, år og behandlingsmåte
* Alle statistikkvariabler

In [63]:
import pandas as pd
import numpy as np

df = pd.read_csv("SSB_14458_Avfall.csv", sep="\t", encoding="latin1")
display(df)

df=df.melt(id_vars=["materialtype", "behandlingsmåte"], 
        value_vars=["Avfallsmengde 2015", "Avfallsmengde 2022"], 
        var_name="År", 
        value_name="tonn")
df["År"] = df["År"].map(lambda streng: int(streng[-4:]))
display(df)

df.pivot(columns="År", values="tonn", index=["materialtype", "behandlingsmåte"])

                            materialtype  ... Avfallsmengde 2022
0    I alt, uten lett forurensede masser  ...               1210
1    I alt, uten lett forurensede masser  ...                425
2    I alt, uten lett forurensede masser  ...                  5
3    I alt, uten lett forurensede masser  ...                 40
4    I alt, uten lett forurensede masser  ...                278
..                                   ...  ...                ...
157              Lett forurensede masser  ...                  0
158              Lett forurensede masser  ...                  1
159              Lett forurensede masser  ...                  1
160              Lett forurensede masser  ...                  9
161              Lett forurensede masser  ...                  1

[162 rows x 4 columns]

                            materialtype  ... tonn
0    I alt, uten lett forurensede masser  ...  893
1    I alt, uten lett forurensede masser  ...  398
2    I alt, uten lett forurensede masser  ...   23
3    I alt, uten lett forurensede masser  ...   70
4    I alt, uten lett forurensede masser  ...  128
..                                   ...  ...  ...
319              Lett forurensede masser  ...    0
320              Lett forurensede masser  ...    1
321              Lett forurensede masser  ...    1
322              Lett forurensede masser  ...    9
323              Lett forurensede masser  ...    1

[324 rows x 4 columns]

År                                                     2015  2022
materialtype       behandlingsmåte
Andre materialer   Annen behandling                       7    33
                   Avfallsbehandling i alt               93    98
                   Brukt som fyll- og/eller dekkmasse     1     0
                   Levert til biogassbehandling           0     1
                   Levert til deponering                 25    33
...                                                     ...   ...
Våtorganisk avfall Levert til deponering                  2     3
                   Levert til forbrenning                16    33
                   Levert til kompostering               16     2
                   Levert til materialgjenvinning        25     8
                   Levert til ukjent behandling           0     7

[162 rows x 2 columns]

# Dataset prepp
* Vi kan smelte/pivotere datasettet om vi vil
* Ellers ser det ut til å være greit å jobbe med fra start

In [64]:
df["materialtype"].unique()

array(['I alt, uten lett forurensede masser', 'Våtorganisk avfall',
       'Park- og hageavfall', 'Treavfall', 'Organisk slam, tørrstoff',
       'Papir, papp og kartong', 'Glass', 'Metall', 'EE-avfall', 'Plast',
       'Gummi', 'Tekstiler', 'Betong og tegl',
       'Slagg, støv, bunnaske, flygeaske', 'Uorganisk slam, tørrstoff',
       'Andre materialer', 'Blandet avfall', 'Lett forurensede masser'],
      dtype=object)

## Undersøkning: Tekstilavfall

* Fra 1. januar 2025 er det ikke lenger lov å kaste tekstiler i restavfall.
* Se [Denne]("https://www.nrk.no/vestfoldogtelemark/na-kan-du-ikke-lenger-kaste-tekstiler-i-restavfallet-1.17182176") artikkelen fra nrk.no
* Har det skjedd noe utvikling i hvordan vi håndterer tekstilavfall mellom 2015 og 2022 som tilsier at vi burde gjøre tiltak for i håndtering av tekstiler?

### Fremgangsmåte
* Bruk filter til å velge ut tekstildata
* Indekser og sorter og bruk slicing til å velge ut tekstildata

In [65]:
#Med indeksering
df = df.pivot(columns="År", values="tonn", index=["materialtype", "behandlingsmåte"])
df.sort_index()

År                                                     2015  2022
materialtype       behandlingsmåte
Andre materialer   Annen behandling                       7    33
                   Avfallsbehandling i alt               93    98
                   Brukt som fyll- og/eller dekkmasse     1     0
                   Levert til biogassbehandling           0     1
                   Levert til deponering                 25    33
...                                                     ...   ...
Våtorganisk avfall Levert til deponering                  2     3
                   Levert til forbrenning                16    33
                   Levert til kompostering               16     2
                   Levert til materialgjenvinning        25     8
                   Levert til ukjent behandling           0     7

[162 rows x 2 columns]

In [66]:
#Undersøk indeksverdier med df.index.get_level_values(0/1).unique()
print("Avfallstyper:\n",df.index.get_level_values(0).unique())
print("behandlingsmåter:\n", df.index.get_level_values(1).unique())

df_tekstiler = df.loc["Tekstiler"]
df_tekstiler

Avfallstyper:
 Index(['Andre materialer', 'Betong og tegl', 'Blandet avfall', 'EE-avfall',
       'Glass', 'Gummi', 'I alt, uten lett forurensede masser',
       'Lett forurensede masser', 'Metall', 'Organisk slam, tørrstoff',
       'Papir, papp og kartong', 'Park- og hageavfall', 'Plast',
       'Slagg, støv, bunnaske, flygeaske', 'Tekstiler', 'Treavfall',
       'Uorganisk slam, tørrstoff', 'Våtorganisk avfall'],
      dtype='object', name='materialtype')
behandlingsmåter:
 Index(['Annen behandling', 'Avfallsbehandling i alt',
       'Brukt som fyll- og/eller dekkmasse', 'Levert til biogassbehandling',
       'Levert til deponering', 'Levert til forbrenning',
       'Levert til kompostering', 'Levert til materialgjenvinning',
       'Levert til ukjent behandling'],
      dtype='object', name='behandlingsmåte')

År                                  2015  2022
behandlingsmåte
Annen behandling                       0     0
Avfallsbehandling i alt                0     1
Brukt som fyll- og/eller dekkmasse     0     0
Levert til biogassbehandling           0     0
Levert til deponering                  0     0
Levert til forbrenning                 0     0
Levert til kompostering                0     0
Levert til materialgjenvinning         0     0
Levert til ukjent behandling           0     0

### Forsvinnende lite data

* Tabell 14458 er industriavfall: De ser ikke ut til å produsere nevneverdig tekstilavfall
* Kan vi finne data om tekstilavfall fra husholdninger?
* Ja: Tabeller [her](https://www.ssb.no/statbank/list/avfkomm)

  Vi finner følgende tabell

### Tabell 13136: 13136: Avfall frå hushalda, etter materiale, behandling og nedstrømsløsning (K) 2015 - 2024 
* Vi må velge 1 region: feks Uttrekk for landet
* Vi velger alle materialer (kunne valgt kun tekstiler), alle nedstrømsløsninger, alle behandlingsmåter og alle tilgjengelige år

In [83]:
df = pd.read_csv("SSB_13136_Husholdningsavfall.csv", sep="\t", encoding="ISO-8859-1") # latin1 encoding
df = df.query("materiale.str.contains('Tekstil')") # Filtrer ut først
df = df.replace(".", np.nan) # "." betyr manglende data -- ".." betyr data kan ikke finnes (ie. kommunen fantas ikke da e.l.)

print("nedstrømsløsninger", df["nedstrømsløsning"].unique())
print("behandlinger", df["behandling"].unique())

nedstrømsløsninger ['I alt' 'Henteordning' 'Gjenvinningsstasjon']
behandlinger ['i alt' 'Materialgjenvinning' 'Forbrenning' 'Deponi' 'Biogassproduksjon'
 'Kompostering' 'Annet']