# Python kommer til excel :)

![her](img/python-excel.gif)

# Introduksjon til *pan*el *da*ta: Pandas

Nyttig ressurs: [https://pandas.pydata.org/docs/user_guide/](https://pandas.pydata.org/docs/user_guide/)

* Pandas er et bibliotek for python for å manipulere og analysere data
* Vi bruker pandas til å laste inn eller lage datasett
    - Rydde opp i data
    - Få det over på annet format
    - Gjøre statistikk
    - Plotte data

* Vi importerer pandas med som regel med `import pandas as pd`
* Pandas er bygd på numpy, så man trenger ofte også å bruke numpy

In [ ]:
#EKSEMPEL

import pandas as pd
import numpy as np
import pickle

with open("HPcharacters.pickle", "rb") as file:
    HPdata = pickle.load(file)

df = pd.DataFrame(HPdata)
df

* Pandas er bygd opp av objekter kalt *DataFrames* og *Series*
* Vi jobber for det meste med DataFrames
* DataFrames likner litt på hvordan man strukturerer data i feks excel
* De består av rader, og kolonner kalt *Series*
<img src="img/dfnavn1.jpg" width="550">

* Hvert rad har en index
* Ut av boksen har radene indeks med heltall 0,1,2,3...
* Man kan også ha navn på radene (indeks er liste med strenger) slik som kolonnenavnene
![dataframe_indeksnavn](img/dfnavn2.png)

## Pandas Series
* Pandas series er som kolonnene i en tabell
* Dataserier har en *index*, et *navn* og *data* av en eller annen datatype (`dtype`)
* Vi lager serier med `pd.Series( ... )`

In [3]:
import pandas as pd
dataserie = pd.Series([1,2,3,4,5])
dataserie2 = pd.Series( ["Bil", "Båt", "Tut", "Bråk"])
print(dataserie2)

0     Bil
1     Båt
2     Tut
3    Bråk
dtype: object

* Her mangler vi navn på serien

* Vi kan navngi serien ved å gi *keyword* argumentet "name"
* `pd.Series(data, name="Navnet")`

In [5]:
dataserie = pd.Series([1,2,3,4,5], name="Heltall")
dataserie

0    1
1    2
2    3
3    4
4    5
Name: Heltall, dtype: int64

* Vi kan gi en annen indeks med *keyword* argumentet "index"
* `pd.Series(data, name="Navnet", index = [ .... ])`

In [6]:
dataserie2 = pd.Series(["Biler", "Båter", "Tuter", "Bråker"], name="transportlyder", 
                       index=["en", "to", "tre", "fire"])
dataserie2

en       Biler
to       Båter
tre      Tuter
fire    Bråker
Name: transportlyder, dtype: object

* Tidligere eksempel gir lister til `pd.Series()`
* Det kan være lurt å lage variabler med listene som skal bruke
* Når det passer seg bør listene være numpy *arrays*

In [12]:
import numpy as np

data = np.array([1,2,3,4,5], dtype="int64") #evt dtype="float64"
navn = "Heltall"
indeks = ["en", "to", "tre", "fire", "fem"]
dataserie = pd.Series(data, name=navn, index=indeks)
#data[2] = 55
dataserie

en      1
to      2
tre     3
fire    4
fem     5
Name: Heltall, dtype: int64

* Merk at dersom vi forandrer datavariabelen, forandres også pandas serien
* Dersom dette ikke er ønskelig kan vi bruke `copy=True` når vi lager serien

In [14]:
import numpy as np

data = np.array([1,2,3,4,5], dtype="int64") #evt dtype="float64"
navn = "Heltall"
indeks = ["en", "to", "tre", "fire", "fem"]
dataserie = pd.Series(data, name=navn, index=indeks, copy=False)
data[2] = 55
dataserie

en       1
to       2
tre     55
fire     4
fem      5
Name: Heltall, dtype: int64

In [22]:
#Kjapt om numpy :)
import numpy as np
pythonliste = [1,2,3,1.4, "hei", ("bla", "tjohei")] #Kalles en liste
print(pythonliste)

numpyarray = np.array([1,2,3,4.0, "hei", "pådeg"]) #Array - Kan ikke blande datatyper

array2d = np.array( [[1,2,3],
                     [4,5,6,7] #ikke lov
                    ])
print(array2d)

array2d[1,1] #numpy indeksering 
#python2dliste[1][1] ...

[1, 2, 3, 1.4, 'hei', ('bla', 'tjohei')]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Oppgave 1:

* Lag dataserien under i pandas:
![oppg1](img/series_oppg1.png)

In [26]:
data = np.array([187,177,195,159], dtype="float64")
navn = "EventyrfigurHøyde"
indeks = ["Per", "Pål", "Espen", "Askeladd"]
dataserie1 = pd.Series(data, name=navn, index=indeks)

Per         187.0
Pål         177.0
Espen       195.0
Askeladd    159.0
Name: EventyrfigurHøyde, dtype: float64

* Vi kan lage serier også med dictionaries `{indeks0: data0, indeks1: data1}`
* Da blir indeksen satt til nøklene i dictionary'en

In [32]:
transport_data = {"land": "bil", "sjø": "båt", "luft": "fly"}
dataserie_transport = pd.Series(transport_data, name="transportmetoder")
transport_data = {"land": "sykkel", "sjø": "båt", "luft": "fly"}
dataserie_transport

land    bil
sjø     båt
luft    fly
Name: transportmetoder, dtype: object

### Oppgave 2:

* Lag samme dataserie som tidligere i pandas
* Denne gangen bruk en dictionary til å sette data/indeks
![oppg1](img/series_oppg1.png)

In [35]:
data_dict = {"Per": 187.0, "Pål": 177.0, "Espen": 195.0, "Askeladd": 159.0}
serie2 = pd.Series(data_dict, name="Eventyrfigurhøyde")
serie2

Per         187.0
Pål         177.0
Espen       195.0
Askeladd    159.0
Name: Eventyrfigurhøyde, dtype: float64

* Dersom vi mangler noe data for en indeks bruker vi `np.NaN`som data

In [40]:
data_dict_mangel = {"Per": 187.0, "Pål": 177.0, "Espen": 195.0, "Askeladd": np.NaN}
serie2mangel = pd.Series(data_dict, name="Eventyrfigurhøyde")
serie2mangel

Per         187.0
Pål         177.0
Espen       195.0
Askeladd      NaN
Name: Eventyrfigurhøyde, dtype: float64

## Pandas DataFrame

* Vi er som regel interessert i å jobbe med DataFrames, en samling av serier
* Vi lager de med `pd.DataFrames(data, index=None, columns=None, dtype=None, copy=None)`
* Vi har de samme feltene som serier, men dataen er nå *todimensjonal*

* `data` variabelen vi fyller dataframen vår med kan ha flere former:
 - 2d-array
 - dictionary -> `{col0: [data0], col1: [data1], ...}`
 - pandas Series

In [50]:
import pandas as pd
import numpy as np
#Med 2D array
data1 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]
                 ])
df1 = pd.DataFrame(data1, columns=["høyde", "vekt", "hodeomkrets"], 
                   index=["baby1", "baby2", "Ambrosius"], copy=True)
data1[2,1] = 256
df1

           høyde  vekt  hodeomkrets
baby1          1     2            3
baby2          4     5            6
Ambrosius      7     8            9

In [56]:
#Med dictionary
data2 =  {"BNP": [1,2,3,4], 
          "levealder": [88,99,75,102], 
          "styresett": ["demokrati", "diktatur", "demokrati", "monarki"]
         }
indeks = ["Norge", "Uganda", "Tyskland", "England"]
df2 = pd.DataFrame(data2, index=indeks)
data2["styresett"][1] = "Representativ republikk"
df2

          BNP  levealder  styresett
Norge       1         88  demokrati
Uganda      2         99   diktatur
Tyskland    3         75  demokrati
England     4        102    monarki

In [59]:
#Med liste av serier
indeks = ["BNP", "levealder", "styresett"]
serie1 = pd.Series([1,88,"demokrati"], name="Norge", index=indeks)
serie2 = pd.Series([2,102,"diktatur"], name="Uganda", index=indeks)
df3 = pd.DataFrame([serie1,serie2])
df3

        BNP  levealder  styresett
Norge     1         88  demokrati
Uganda    2        102   diktatur

### Oppgave 3:


Under har vi et lite pandas dataframe.
![oppg1](img/dataframe_oppg3.png)

Prøv å lage tabellen ved å bruke metodene over

## Slå opp i Frame/Series

### Series
* Vi kan slå opp verdi nr. $i$ med serie[$i$]
* Eller vi kan bruke indeks: serie["indeks"]

### Dataframes
* Vi får tak i kolonne med `df["kolonnenavn"]`
* Vi får tak i rad med df.loc["rad_indeks"]
* Vi kan få tak i rad med df.iloc[i] hvor i er mellom 0 og antall rader i tabellen
* Vi får tak i et datapunkt med df.loc["rad", "kolonne"]

In [ ]:
#kolonne BNP:


#Rad med indeks


#Rad med radnummer

#Levalder i England:

### Oppg 4

Se at du kan slå opp fra oppgave 3 og hente ut en gitt kolonne, rad eller datapunkt

## Manipulere Frame/Series

Vi vil kanskje kunne trenge å:
* Forandre indeks, navn på serie, eller navn på kolonner
* Legge til rad, eller kolonne til dataframe
* Bytte om på rad/kolonne
* Fjerne rad eller kolonne

In [ ]:
data_land = ["England", "Norge", "Sverige"]
land = pd.Series(data_land)

#Forandre/hente navn på serie med min_serie.name


indeks = ["GB", "NO", "SE"]

#Hent eller sett en series index med min_serie.index


#land.index[1] = "DK" Vi må skifte hele indeksen


#Vi legger til nye element på samme måte som i dictionaries
 # Legg til nytt element.

 #Skift navn 
#Merk at .rename() ikke skifter navnet, men returnerer en ny Serie med skiftet
 #inplace=True gjør "fikser" på dette
land

In [ ]:
data_innbyggere = [56, 6, 10]
land_innbyggere = pd.Series(data_innbyggere, name="innbyggere", index=indeks)

 #Lager dataframe med de to seriene
 # Bytter om på kolonner/rader (Transponerer)
 #Nytt navn til kolonne
 #Skifter landenavn til island
 #antall innbyggere til 0.4
 #Nytt navn på indeks "DK"
 # Oppdaterer data

 #Legg til ny rad
 #Legg til rad med manglende data
 #Oppdater data
df_land

### Oppg 5:
Ta utgangpunkt i tabellen over for å lage tabellen under
![oppg5](img/df_oppg5v2.png)

les [her](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html) for å finne ut hvordan du legger til en kolonne med `insert`

### Oppg 6
Hva er gjennomsnittlig arbeidsledighet til landene over?