# Store datasett - I Excel

- Excel er supert helt til filen din har 1,5 mill. rader og kræsjer PC-en din så grundig at sjefen ikke vet om han skal sparke eller ansette på IT

- Å jobbe med data i Excel er helt supert helt til du må gjøre den samme nedlastingen og opprydding hver mandag morgen i 3 år

# **Pan**el**da**ta:
## Pandas 🐼
- Industristandard for dataanalyse
- Behandler enorme mengder data lynraskt
- Relativt lett i bruk til å være et så kraftig verktøy

- Pandas leser nesten alt av filer (csv, Excel, SQL, JSON..)
- Pandas+Python lar oss automatisere alt fra innhenting av data, til vasking, sammenslåing, analyse og visualisering

In [1]:
import pandas as pd

# Lag en enkel DataFrame på 1-2-3
data = {
    'Navn': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 92, 78],
    'Status': ['Bestått', 'Bestått', 'Vurderes']
}

df = pd.DataFrame(data)
df

      Navn  Score    Status
0    Alice     85   Bestått
1      Bob     92   Bestått
2  Charlie     78  Vurderes

- Et dataframe er 2d, og bygget opp av rader og kolonner som av typen pandas `Series`.
- Pythonbiblioteket inneholder ferdig funksjonalitet som lar oss gjøre veldig mye av statistikk og databehandlig.
  - Gruppere, slå sammen data, filtere, deskriptiv statistikk (snitt, standardavvik, korrelasjon osv), plotte osv

### Basics: Hente ut kolonner og rader

- Vi henter ut 1 kolonne ved å gi kolonnenavnet i klammeparanteser bak dataframe-variabelen

In [2]:
#Henter ut navnekolonnen -> Series   
df["Score"]

0    85
1    92
2    78
Name: Score, dtype: int64

Vi kan hente ut flere kolonner ved å bruke en kommaseparert liste i klammeparantes, inne i de første klammene

In [3]:
#Henter ut Navn og Score kolonner -> Dataframe
df[["Navn", "Score"]]

      Navn  Score
0    Alice     85
1      Bob     92
2  Charlie     78

Vi henter ut rader med `df.loc[«radnavn»]`

In [4]:
#Hent ut rad 2
df.loc[2]
df.set_index("Navn").loc["Alice"]

Score          85
Status    Bestått
Name: Alice, dtype: object

###

`.loc[]` bruker vi også til å velge *både* rader og kolonner

In [5]:
# Hent ut rad 0 og 2, og kolonner "Navn" og "Status"
df.loc[[0,2], ["Status", "Navn"]]
df.iloc[0:2]

    Navn  Score   Status
0  Alice     85  Bestått
1    Bob     92  Bestått

## Attributter og metoder
- Et spesifikt objekt som `Dataframe` eksempelet vårt `df`, eller `Series`objektet `df["Score"]` har både attributter og metoder.
- En attributt er litt som en innebygd variabel, mens en metode er som en innebygd funksjon.
- Vi bruker punktum til å hente ut og brukke disse metodene og attributtene:

In [6]:
#Attributt: En indeks med kolonnenavn
df["Score"].name

'Score'

In [7]:
# .describe() - En funksjon som vi kaller uten argumenter og spytter ut statistikk
df.describe()

       Score
count    3.0
mean    85.0
std      7.0
min     78.0
25%     81.5
50%     85.0
75%     88.5
max     92.0

In [8]:
print("Gjennomsnittsscore:", df["Score"].mean()) # Bruker dataseriens innebygde funksjon .mean() som spytter ut gjennomsnitt 
print("Dataseriens navn er: ", df["Score"].name ) #Name er en attributt

Gjennomsnittsscore: 85.0
Dataseriens navn er:  Score

# Liste over innebygde attributter og metoder
## Series

### Series atributter

Dataseriene vi lager har flere *atributter*

| **Attributt**      | **Beskrivelse**                                                                  |
|--------------------|----------------------------------------------------------------------------------|
| `index`            | Indeksen (labels) for Series.                                                    |
| `values`           | Verdiene (data) i Series som en NumPy-array.                                     |
| `name`             | Navnet på Series.                                                                |
| `dtype`            | Datatypen for verdiene i Series.                                                 |
| `size`             | Antall elementer i Series.                                                       |
| `shape`            | Dimensjonaliteten til Series (alltid en enkelt dimensjon).                       |
| `empty`            | Returnerer `True` hvis Series er tom (dvs. ikke har noen elementer).              |
| `nbytes`           | Det totale antallet bytes som forbrukes av elementene i Series.                  |
| `hasnans`          | Returnerer `True` hvis det finnes noen `NaN`-verdier i Series.                   |
| `is_unique`        | Returnerer `True` hvis alle verdiene i Series er unike.                          |
| `is_monotonic`     | Returnerer `True` hvis Series er sortert i stigende rekkefølge.                  |
| `str`              | Gir tilgang til strengmetoder (hvis Series inneholder strenger).                 |
| `dt`               | Gir tilgang til datetime-metoder (hvis Series inneholder datetime-objekter).     |

### Series Metoder
En pandas dataserie har mange nyttige innebygde metoder som gjør ting med dataen:

| **Metode**            | **Beskrivelse**                                                                  |
|-----------------------|----------------------------------------------------------------------------------|
| `head(n)`             | Returnerer de første `n` elementene i Series (standard er 5).                     |
| `tail(n)`             | Returnerer de siste `n` elementene i Series (standard er 5).                      |
| `unique()`            | Returnerer unike verdier i Series.                                                |
| `value_counts()`      | Returnerer antall forekomster av unike verdier i Series.                          |
| `describe()`          | Genererer beskrivende statistikk som antall, gjennomsnitt, std, min og maks.      |
| `sum()`               | Returnerer summen av elementene i Series.                                         |
| `mean()`              | Returnerer gjennomsnittet av elementene i Series.                                 |
| `median()`            | Returnerer medianen av elementene i Series.                                       |
| `min()`               | Returnerer minimumsverdien i Series.                                              |
| `max()`               | Returnerer maksimumsverdien i Series.                                             |
| `std()`               | Returnerer standardavviket til Series.                                            |
| `sort_values()`       | Sorterer Series etter verdiene.                                                   |
| `sort_index()`        | Sorterer Series etter indeksen.                                                   |
| `apply(func)`         | Anvender en funksjon element for element på Series.                               |
| `map(func)`           | Mapper verdier i Series ved hjelp av funksjon eller dictionary.                       |
| `dropna()`            | Fjerner `NaN`-verdier fra Series.                                                 |
| `fillna(value)`       | Fyller inn `NaN`-verdier med en spesifisert verdi.                                |
| `astype(dtype)`       | Endrer datatypen til Series til spesifisert datatype.                             |
| `clip(lower, upper)`  | Begrenser verdier til et spesifisert område (nedre og øvre grenser).              |
| `between(left, right)`| Returnerer True for verdier mellom spesifiserte grenser.                          |
| `shift(periods)`      | Skifter verdiene med et spesifisert antall perioder.                             |
| `cumsum()`            | Returnerer den kumulative summen av elementene i Series.                          |
| `cumprod()`           | Returnerer det kumulative produktet av elementene i Series.                       |
| `rolling(window)`     | Gir glidende beregninger med et gitt vindu                                          |
| `expanding()`         | Gir ekspanderende beregninger (f.eks. kumulative beregninger).               |
| `resample(rule)`      | Resampler tidsseriedata i henhold til en spesifisert frekvens.                    |
| `plot()`              | Plotter dataen i Series ved hjelp av Matplotlib.                                  |

# Mye....
- Vi begynner ikke å liste om for `Dataframes`
- Her er det lurt å spørre en KI-om hjelp, eller slå opp i [dokumentasjonen](https://pandas.pydata.org/docs/reference/index.html)

# CSV og store datasett
- I morgen skal dere jobbe dere gjennom:
[CSV og store datasett](https://iirevu.org.ntnu.no/iira6001/notebooks/Fyrste%20datasett%20med%20CSV.html)
- Målet er å laste inn, «vaske» og plotte valutakurser fra den relativt store csv-filen fra norges bank